y-scope/clp

- components/core/tools/docker-images/clp-env-base-bionic/Dockerfile
- components/core/tools/docker-images/clp-env-base-centos7.4/Dockerfile
- components/core/tools/docker-images/clp-env-base-centos7.4/setup-scripts/git
- components/core/tools/docker-images/clp-env-base-focal/Dockerfile
- tools/docker-images/clp-execution-base-focal/Dockerfile
Necessary for some Github actions that cannot be configured to use a bash shell with .bashrc loaded
> Forcibly enable the SCL git package in the centos 7.4 dependency image; Minor refactoring of Docker files

- .github/workflows/clp-core-build.yaml
- .github/workflows/clp-dependency-image-build.yaml
- .github/workflows/clp-execution-image-build.yaml
Changes
- The clp core build workflow requires the newest version of the dependency images published by the clp dependencies build workflow
- Added a concurrency group to pause the clp core build workflow if there is a concurrent dependency build workflow running
- Added a trigger to the clp core build workflow on the completion of a dependency build workflow
Validation
- Tested workflows on fork
> Added Workflow Dependencies

- components/core/src/FileWriter.cpp
Fixes #44 
* Ran the reproduction steps in #44 and ensured they succeeded
* Compressed and decompressed a dataset
* Diffed the dataset with the decompressed output to ensure lossless compression
> Use stat+fopen instead of mknod to create a file if it doesn't exist (fixes #44)

- components/job-orchestration/requirements.txt
CVE-2021-23727
* Built package with Celery 5.2.2
* Compressed and decompressed a dataset
* Diffed the dataset with the decompressed output to ensure lossless compression
> Update Celery to 5.2.2 to prevent CVE-2021-23727

- components/package-template/src/sbin/compress
... and minor logging fixes.
#29 
The container cannot compress relative paths since it does not know the root of the path. So instead, we:
* Resolve input paths passed to `sbin/compress` before passing them to the container.
* Raise an error if the user specifies relative paths in a list of paths for compression (`sbin/compress --input-list`).
* Compressed a relative path
* Tried to compress a list of relative paths and validated that an error was raised
* Compress a list of absolute paths
> Resolve input paths for compression before passing them to the container

- components/core/tools/scripts/lib_install/fmtlib.sh
- components/core/tools/scripts/lib_install/libarchive.sh
- components/core/tools/scripts/lib_install/lz4.sh
- components/core/tools/scripts/lib_install/mariadb-connector-c.sh
- components/core/tools/scripts/lib_install/spdlog.sh
- components/core/tools/scripts/lib_install/zstandard.sh
* Refactor CLP core's library installation scripts to be simpler
* Add the ability to specify an output directory for the .deb package generated by building the package (useful to avoid recompilation on a different machine)
* Built clp-env-base:focal docker image and verified that CLP's core could be built within it.
> Refactor library installation scripts and add ability to specify output directory for generated .deb package.

- components/core/README.md
- components/core/tools/docker-images/clp-env-base-bionic/setup-scripts/install-prebuilt-packages.sh
- components/core/tools/docker-images/clp-env-base-centos7.4/setup-scripts/install-boost.sh
- components/core/tools/docker-images/clp-env-base-centos7.4/setup-scripts/install-cmake.sh
- components/core/tools/docker-images/clp-env-base-centos7.4/setup-scripts/install-prebuilt-packages.sh
- components/core/tools/docker-images/clp-env-base-focal/setup-scripts/install-prebuilt-packages.sh
- components/core/tools/scripts/lib_install/fmtlib.sh
- components/core/tools/scripts/lib_install/libarchive.sh
- components/core/tools/scripts/lib_install/lz4.sh
- components/core/tools/scripts/lib_install/mariadb-connector-c.sh
- components/core/tools/scripts/lib_install/spdlog.sh
- components/core/tools/scripts/lib_install/zstandard.sh
- tools/docker-images/clp-execution-base-focal/setup-scripts/install-prebuilt-packages.sh
Fixes bug in #57 
* Rely on users / containers installing the necessary dependencies for the library installation scripts rather than having them in the scripts themselves. This is because each distro may be have different package managers, etc. which make the scripts unwieldy.
* Replace wget with curl since curl is preinstalled in some Linux distributions.
* Built all docker images successfully.
* Verified CLP's core builds in each dependency container.
* Verified CLP runs in the execution container.
> Bugfix: Extract dependency installation from CLP core's library installation scripts; Replace usage of wget with curl.

- .github/actions/clp-docker-build-push-action/action.yaml
- .github/workflows/clp-core-build.yaml
- .github/workflows/clp-dependency-image-build.yaml
- .github/workflows/clp-execution-image-build.yaml
- Github Build Worfklows have been failing in every PR because the local `clp-docker-build-push-action`, which is used across several workflows, builds a docker image and tries to push it to `ghcr` - pushing to the registry from a PR is blocked, causing failed execution of workflows
- The `generate-build-dependency-image` workflow currently takes upwards of 40 mins to finish. Reorganize different build steps in the workflow to execute in paralell - takes 20 mins to finish.
- Using this PR to validate no docker image push on PRs
- https://github.com/NamanGulati/clp/actions/runs/2156157051
> Refactor Workflows & block docker push on PR

- components/core/CMakeLists.txt
- components/core/cmake/utils.cmake
- components/core/src/DictionaryReader.hpp
- components/core/src/DictionaryWriter.hpp
- components/core/src/LogTypeDictionaryEntry.cpp
- components/core/src/LogTypeDictionaryEntry.hpp
- components/core/src/VariableDictionaryEntry.cpp
- components/core/src/VariableDictionaryEntry.hpp
- components/core/src/dictionary_utils.cpp
- components/core/src/dictionary_utils.hpp
- components/core/src/streaming_archive/reader/Segment.hpp
- components/core/src/streaming_archive/writer/Segment.cpp
- components/core/src/streaming_archive/writer/Segment.hpp
- components/core/src/streaming_compression/Decompressor.hpp
- components/core/src/streaming_compression/passthrough/Decompressor.cpp
- components/core/src/streaming_compression/passthrough/Decompressor.hpp
- components/core/src/streaming_compression/zstd/Decompressor.cpp
- components/core/src/streaming_compression/zstd/Decompressor.hpp
* Extends passthrough compression to the dictionaries.
* Updates the passthrough compressor/decompressor classes to support compression/decompression from file.
* Adds a new CMake property to choose between Zstandard and Passthrough compression.
* Compressed and decompressed a log dataset losslessly.
> Extend passthrough compression to the dictionaries

- components/core/tools/docker-images/clp-env-base-bionic/Dockerfile
- components/core/tools/docker-images/clp-env-base-bionic/build.sh
- components/core/tools/docker-images/clp-env-base-centos7.4/Dockerfile
- components/core/tools/docker-images/clp-env-base-centos7.4/build.sh
- components/core/tools/docker-images/clp-env-base-focal/Dockerfile
- components/core/tools/docker-images/clp-env-base-focal/build.sh
- tools/docker-images/clp-execution-base-focal/Dockerfile
- tools/docker-images/clp-execution-base-focal/build.sh
#61 
- Set the working directory of all containers so that it's accessible by any non-root user
- Add a script to build `tools/docker-images/clp-execution-base-focal`
- Make the names of all containers consistent with those on GitHub
* Built all containers using the associated build scripts.
* Verified that they could all be run as a non-root user (`docker run -it -u$(id -u):$(id -g) <container image> /bin/bash`)
> Fix for #61 and a few associated changes

- .github/workflows/clp-execution-image-build.yaml
#63 
It seems GitHub doesn't like a preceding `./` in the monitored paths for a workflow, so this change removes it.
Tested the workflow was triggered in a forked clp repo.
> Trigger clp-execution-image-build workflow on changes to clp-execution-base-focal container files (fixes #63).

- components/core/tools/scripts/utils/README.md
- components/core/tools/scripts/utils/run-in-container.sh
The package currently runs in an Ubuntu 20.04 container, so to develop CLP core and run it in the package, you either have to be developing on Ubuntu 20.04 already or you have to rebuild the package every time you change CLP core.
This change adds a script that allows us to build CLP core in an Ubuntu 20.04 container containing CLP core's dependencies. The built binaries can then be copied to the package without rebuilding the package. Note that the script runs any command you give it from the root of CLP core.
* Used the script to build CLP core from an Ubuntu 18.04 machine.
* Tested that the built binaries worked in the CLP package.
> Add script to run commands in CLP core's dependency container

- components/clp-py-utils/clp_py_utils/initialize-orchestration-db.py
- components/compression-job-handler/compression_job_handler/compression_job_handler.py
- components/core/CMakeLists.txt
- components/core/README.md
- components/core/src/PThread.cpp
- components/core/src/PThread.hpp
- components/core/src/clo/CommandLineArguments.cpp
- components/core/src/clo/CommandLineArguments.hpp
- components/core/src/clo/ControllerMonitoringThread.cpp
- components/core/src/clo/ControllerMonitoringThread.hpp
- components/core/src/clo/clo.cpp
- components/core/src/networking/SocketOperationFailed.cpp
- components/core/src/networking/SocketOperationFailed.hpp
- components/core/src/networking/socket_utils.cpp
- components/core/src/networking/socket_utils.hpp
- components/core/tools/docker-images/clp-env-base-bionic/setup-scripts/install-packages-from-source.sh
- components/core/tools/docker-images/clp-env-base-centos7.4/setup-scripts/install-packages-from-source.sh
- components/core/tools/docker-images/clp-env-base-focal/setup-scripts/install-packages-from-source.sh
- components/core/tools/scripts/lib_install/msgpack.sh
- components/job-orchestration/job_orchestration/executor/celeryconfig.py
- components/job-orchestration/job_orchestration/executor/compression_task.py
- components/job-orchestration/job_orchestration/executor/search_task.py
- components/job-orchestration/job_orchestration/job_config.py
- components/job-orchestration/job_orchestration/scheduler/scheduler.py
- components/job-orchestration/job_orchestration/scheduler/scheduler_data.py
- components/package-template/src/sbin/native/search
- components/package-template/src/sbin/search
- components/package-template/src/sbin/start-clp
- tools/packager/install-scripts/install-core.sh
Added basic support for distributed search using the celery workers. The algorithm is essentially as follows:
* The search script starts up the search controller which is a TCP server.
* The search script also creates a task for every archive in the database and submits them to the scheduler through the database.
* The scheduler picks up the tasks from the database and queues them for workers.
* A worker picks up a task from the queue, connects to the search controller, runs the search on the corresponding archive and sends any results to the search controller.
* The search controller prints any results it receives.
* Compressed some logs and verified decompression.
* Searched the same logs for some text and verified it returned relevant results.
* Verified that tasks were created for …
> Basic implementation of distributed search following the conventions of distributed compression using Celery.

- components/core/src/streaming_archive/MetadataDB.cpp
#69 
* The timestamp filtering criteria for filtering files from the database was flawed: It only returned files that fit entirely within the given timestamp range, rather than also returning those which partially overlapped with the given timestamp range.
* This change fixes that and adds a comment so the next developer doesn't make the same silly mistake.
* Compressed the dataset mentioned by the issue.
* Verified the searches mentioned by the issue worked.
* Verified that searches with a timestamp filter that overlapped with a certain file's timestamp range worked, no matter if it the overlap was a complete or partial.
> Bug-fix: Undo logic error in how database timestamp filtering criteria was set (fixes #69).

- components/core/src/LogTypeDictionaryWriter.cpp
#75 
Removed the check which prevents compressing messages with just a timestamp and no content.
* Validated compressing and decompressing logs including those containing messages with no content.
* Validated searching the same logs.
> Allow an empty log type (fixes #75).

- components/core/CMakeLists.txt
- components/core/README.md
- components/core/cmake/utils.cmake
- components/core/src/DictionaryReader.hpp
- components/core/src/Grep.cpp
- components/core/src/Profiler.cpp
- components/core/src/Profiler.hpp
- components/core/src/Stopwatch.cpp
- components/core/src/Stopwatch.hpp
- components/core/src/Utils.cpp
- components/core/src/clg/clg.cpp
- components/core/src/clo/clo.cpp
- components/core/src/clp/clp.cpp
- components/core/src/streaming_archive/reader/Archive.cpp
- components/core/src/streaming_archive/reader/File.cpp
- components/core/src/streaming_archive/writer/Archive.cpp
- components/core/tools/docker-images/clp-env-base-bionic/setup-scripts/install-prebuilt-packages.sh
- components/core/tools/docker-images/clp-env-base-centos7.4/Dockerfile
- components/core/tools/docker-images/clp-env-base-centos7.4/setup-scripts/install-prebuilt-packages.sh
Before open-sourcing, some old profiling code was not removed and even though everything was single-threaded, the Profiler class was still using atomics to store measurements. This change resolves those issues and makes some other improvements:
- Remove remnants of old profiling
- Use Stopwatch instead of atomics for Profiler measurements to avoid the overhead for single-threaded code (multi-threaded code can use a different Profiler implementation in the future)
- Use templates instead of macros for more compile-time checking
- Switch from C++14 to C++17 to support the above changes
- Tested that when `PROF_ENABLED=0`, profiling was disabled and used `objdump -d` to verify that no profiling code was added to the binaries.
- Tested that when `PROF_ENABLED=1`, the existing profiling code …
> Improvements to the profiling code

- components/clp-py-utils/clp_py_utils/initialize-orchestration-db.py
- components/compression-job-handler/compression_job_handler/compression_job_handler.py
- components/job-orchestration/job_orchestration/executor/celeryconfig.py
- components/job-orchestration/job_orchestration/executor/compression_task.py
- components/job-orchestration/job_orchestration/executor/search_task.py
- components/job-orchestration/job_orchestration/scheduler/constants.py
- components/job-orchestration/job_orchestration/scheduler/scheduler.py
- components/job-orchestration/job_orchestration/scheduler/scheduler_data.py
- components/package-template/src/sbin/native/search
- components/package-template/src/sbin/start-clp
#79 
* zstandard was being transitively included in the package start-up script which runs natively on the user's machine.
* zstandard uses a native library and the native library may be incompatible with a user's Python/OS, so such a user would not be able to start the package.
* This change splits the things that the start-up script needs into its own module so that zstandard is not transitively included.
Built the package and ran it on a machine that couldn't use the native Zstandard library included in the package.
> Move scheduler constants into their own module so that packages with native dependencies are not transitively included in the package start-up script.

- components/core/src/DictionaryReader.hpp
- components/core/src/Grep.cpp
- components/core/src/Utils.cpp
- components/core/src/Utils.hpp
- components/core/tests/test-Utils.cpp
When doing wildcard-matching between strings like `"123"` and `"1*3"`, the wildcard matching method would access a character outside the input string buffers. This is a remnant of when we used C-strings which had a terminating null. This bug isn't triggered in production because all current searches are substring matches (i.e., with prefix and suffix `'*'`). 
This PR fixes the issue and achieves a slight performance improvement by omitting some checks which are unnecessary if the caller cleans up the wildcard string. Unnecessary methods and unit tests are also removed.
Verified all unit tests (including those with prefix and suffix `'*'`) passed.
> Fix out-of-bounds access when doing wildcard match without prefix and suffix '*'.

- components/core/src/Utils.cpp
- components/core/src/Utils.hpp
- components/core/tests/test-Utils.cpp
#84 
* The previous use of `strtoll` erroneously checked for a range error only on the positive side.
* Instead of continuing to use `strtoll`, this PR switches to C++17's `from_chars` which allows us to use `string_view`s and achieves better performance.
* Verified with a new unit test which tests integers at the boundary and just outside the representable range.
* Verified lossless compression and decompression of logs with integers less than -2^63.
* Verified lossless compression and decompression of logs with integers within the range of int64.
> Switch from strtoll to C++17's from_chars (fixes #84)

- components/core/src/string_utils.cpp
- components/core/src/string_utils.hpp
- components/core/tests/test-string_utils.cpp
`string_utils` depends on `boost::to_lower` which forces FFI libraries to depend on it. This PR replaces `boost::to_lower` with our own method.
Validated with a unit test.
> Remove boost dependency from string_utils so that FFI libraries don't depend on it.

- components/compression-job-handler/README.md
- components/job-orchestration/README.md
- The proposed changes are something I had to make to get CLP up and running on my Ubuntu instance.
- The code in the README.md for copying `compression-job-handler` and ` job-orchestration ` packages is misplaced. 
- I have highlighted line numbers as well as made corrections where necessary. 
- I have followed the said steps and got CLP up and running on my Ubuntu box. 
- On the other hand, if someone tries to follow current directions, they'd either get confused or end up copying `clp-py-utils` directory again and again. 
- At the end, they will not be able to run the `start` or `compress` commands as the necessary packages won't be there.
> Documentation and Code Corrections

- components/core/CMakeLists.txt
- components/core/src/Defs.h
- components/core/src/EncodedVariableInterpreter.cpp
- components/core/src/GlobalMySQLMetadataDB.cpp
- components/core/src/GlobalSQLiteMetadataDB.cpp
- components/core/src/Profiler.cpp
- components/core/src/Profiler.hpp
- components/core/src/ffi/encoding_methods.cpp
- components/core/src/ffi/encoding_methods.tpp
- components/core/src/streaming_archive/MetadataDB.cpp
- components/core/src/type_utils.hpp
We're using C++17, so we don't have access to `bit_cast` (C++20) just yet. This PR moves the bit casting logic we were using everywhere into a method. Also, it moves such type utilities into their own file.
* Verified that the compiler generated assembly is the same even after moving the code into a method.
* Verified unit tests pass.
> Move memcpy-based casting (bit_cast) into a method and move type utilities into their own file.

- components/core/src/ffi/encoding_methods.cpp
- components/core/src/ffi/encoding_methods.hpp
- components/core/tests/test-encoding_methods.cpp
The existing logging libraries (e.g., [clp-logging](https://pypi.org/project/clp-logging/)) use different delimiters and encoding methods for variables. This commit switches to the same for consistency and assigns version names for bookkeeping. Note that the libraries use the compact variable encoding (4 bytes per encoded variable) whereas the FFI uses the standard variable encoding (8 bytes per encoded variable).
Verified the unit tests passed.
> FFI: Make variable encoding methods and schema match those of the existing CLP logging libraries; Add a version name for each.

- components/core/src/ffi/encoding_methods.cpp
- components/core/src/ffi/encoding_methods.hpp
- components/core/tests/test-encoding_methods.cpp
As we evaluate more data sets, we've found that making '/' is a delimiter can sometimes result in a significant increase in compression ratio. In addition, we haven't found any data set where it decreases compression ratio. This commit adds '/' as a delimiter and updates the version name for the default variable schemas.e
Verified that the unit tests pass.
> FFI: Make '/' a delimiter in the default variables schema to achieve better compression ratio.

- .github/workflows/clp-core-build.yaml
- .github/workflows/clp-dependency-image-build.yaml
- .github/workflows/clp-execution-image-build.yaml
- .gitmodules
- components/core/tools/scripts/deps-download/download-all.sh
Dependent projects that use this one as a submodule sometimes need to use this project's submodules. Since we use a script to download submodules (rather than using git submodules), that means the dependent projects would need to execute that script manually after cloning the repo. For automated checkout scripts, this is an extra step and set of dependencies they need to maintain.
The original reason we switched from git submodules to downloads (#31) is because the source release generated by GitHub doesn't include the submodules, and since the release is not a git repo, we can't download the submodules after the fact.
This PR allows us to use git submodules if the local dir is a git repo and falls back to downloads if not. The one exception to this is sqlite3 where we always download it …
> Use git submodules rather than downloads when the local dir is a git repo.

- components/core/CMakeLists.txt
- components/core/src/ffi/ir_stream/byteswap.hpp
- components/core/src/ffi/ir_stream/encoding_methods.cpp
macOS doesn't have byteswap.h so we need to use macOS-specific macros for swapping bytes.
Verified that byteswap.h no longer caused build failures of y-scope/clp-ffi-java#20 on macOS.
> Add shim for byteswap.h on macOS.

- components/core/CMakeLists.txt
- components/core/README.md
- components/core/tools/docker-images/clp-env-base-bionic/setup-scripts/install-packages-from-source.sh
- components/core/tools/docker-images/clp-env-base-centos7.4/setup-scripts/install-packages-from-source.sh
- components/core/tools/docker-images/clp-env-base-focal/setup-scripts/install-packages-from-source.sh
This update is necessary for two reasons:
* v5 is the latest version available from [Homebrew](https://formulae.brew.sh/formula/msgpack-cxx#default), so to build CLP on macOS, we need to support it.
* v5 changes the name of the C++ library from `msgpack` to `msgpackc-cxx`, so it's best to update early to avoid having too many people install older versions.
* Installed v5 in the dependency container
* Built the package using the new container
* Compressed some logs using the package
* Validate that search still worked
> Update to msgpackc-cxx 5.

- components/core/src/Grep.cpp
- components/core/src/Query.cpp
- components/core/src/Query.hpp
- components/core/src/Utils.cpp
- components/core/src/Utils.hpp
- components/core/src/clg/clg.cpp
- components/core/src/clo/clo.cpp
- components/core/src/clp/FileDecompressor.cpp
- components/core/src/streaming_archive/Constants.hpp
- components/core/src/streaming_archive/reader/Archive.cpp
- components/core/src/streaming_archive/reader/Archive.hpp
- components/core/src/streaming_archive/reader/File.cpp
- components/core/src/streaming_archive/reader/File.hpp
- components/core/src/streaming_archive/writer/Archive.cpp
- components/core/src/streaming_archive/writer/Archive.hpp
#39
* #39 removed the ability to write encoded files to disk *without* storing them in a segment, but it didn't remove the corresponding read-side of the code. This PR removes the read-side of the code.
* This PR also refactors some line-length violations as a result of updates to code style. Not all violations were corrected to avoid making the PR confusing to read.
* Unit tests passed.
* Compressed, decompressed, and searched the [openstack-24hr](https://zenodo.org/record/7094972#.Y-AsKnbMKHt) dataset using `clp`, `clg`, and the `compress` and `search` scripts from the package; validated that the output was the same as before the PR.
> Remove obsolete code for reading columns stored outside a segment.

- .github/actions/clp-docker-build-push-action/action.yaml
- .github/workflows/clp-core-build.yaml
- .github/workflows/clp-dependency-image-build.yaml
- .github/workflows/clp-execution-image-build.yaml
Currently, the GitHub workflows are only enabled for pushes and PRs to the main branch. This is fine for the main repo since we don't use many branches in the main repo. However, it's not very useful for forks: they would need to push/PR to their own main branch to get the workflows to run.
This PR enables workflows to run on all branches while continuing to ensure that the generated Docker images are not pushed to GitHub Packages except when there's a commit to the main branch.
The workflows ran [successfully](https://github.com/kirkrodrigues/clp/actions) on the branch that this PR comes from.
> Enable GitHub workflows on all branches.

- components/core/README.md
- components/core/tools/docker-images/clp-env-base-bionic/Dockerfile
- components/core/tools/docker-images/clp-env-base-centos7.4/Dockerfile
- components/core/tools/docker-images/clp-env-base-focal/Dockerfile
- components/core/tools/scripts/lib_install/centos7.4/README.md
- components/core/tools/scripts/lib_install/centos7.4/install-all.sh
- components/core/tools/scripts/lib_install/centos7.4/install-packages-from-source.sh
- components/core/tools/scripts/lib_install/centos7.4/install-prebuilt-packages.sh
- components/core/tools/scripts/lib_install/install-boost.sh
- components/core/tools/scripts/lib_install/install-cmake.sh
- components/core/tools/scripts/lib_install/ubuntu-bionic/README.md
- components/core/tools/scripts/lib_install/ubuntu-bionic/install-all.sh
- components/core/tools/scripts/lib_install/ubuntu-bionic/install-packages-from-source.sh
- components/core/tools/scripts/lib_install/ubuntu-bionic/install-prebuilt-packages.sh
- components/core/tools/scripts/lib_install/ubuntu-focal/README.md
- components/core/tools/scripts/lib_install/ubuntu-focal/install-all.sh
- components/core/tools/scripts/lib_install/ubuntu-focal/install-packages-from-source.sh
- components/core/tools/scripts/lib_install/ubuntu-focal/install-prebuilt-packages.sh
As we support building clp-core on more platforms, the instructions for installing dependencies are starting starting to clutter the README. This PR instead moves the instructions into platform-specific folders.
In addition, the containers currently use scripts to install the dependencies that have to be kept in-sync with the READMEs. This PR also changes the READMEs to simply ask the users to run the scripts directly.
Container images built successfully.
> Reorganize clp-core's dependency-installation scripts so that users can call them directly.

- .github/actions/clp-core-build/action.yaml
- .github/workflows/clp-core-build.yaml
- components/core/CMakeLists.txt
- components/core/cmake/Modules/FindLZ4.cmake
- components/core/cmake/Modules/FindLibArchive.cmake
- components/core/cmake/Modules/FindLibraryDependencies.cmake
- components/core/cmake/Modules/FindMariaDBClient.cmake
- components/core/cmake/Modules/FindZStd.cmake
- components/core/src/FileWriter.cpp
- components/core/src/GlobalMetadataDB.hpp
- components/core/src/GlobalMySQLMetadataDB.cpp
- components/core/src/GlobalMySQLMetadataDB.hpp
- components/core/src/GlobalSQLiteMetadataDB.cpp
- components/core/src/GlobalSQLiteMetadataDB.hpp
- components/core/src/PageAllocatedVector.hpp
- components/core/src/Platform.hpp
- components/core/src/Utils.cpp
- components/core/src/Utils.hpp
- components/core/src/streaming_archive/writer/File.hpp
- components/core/tests/test-Segment.cpp
- components/core/tools/scripts/lib_install/macos-12/README.md
- components/core/tools/scripts/lib_install/macos-12/install-all.sh
This PR adds some compilation fixes and platform-specific code to build CLP's core on macOS; in addition, it adds a GitHub workflow job to test building CLP's core on macOS 12.
Each step is split up into a different commit.
* Built all CLP core executables on macOS.
* Validated compression, decompression, and search of the [openstack-24hr](https://zenodo.org/record/7094972#.Y-AsKnbMKHt) dataset.
> Add support for building clp-core on macOS

- .github/workflows/clp-core-build.yaml
- components/core/CMakeLists.txt
- components/core/cmake/Modules/FindLibArchive.cmake
- components/core/tools/scripts/lib_install/centos7.4/install-packages-from-source.sh
- components/core/tools/scripts/lib_install/fmtlib.sh
- components/core/tools/scripts/lib_install/libarchive.sh
- components/core/tools/scripts/lib_install/lz4.sh
- components/core/tools/scripts/lib_install/macos-12/install-all.sh
- components/core/tools/scripts/lib_install/mariadb-connector-c.sh
- components/core/tools/scripts/lib_install/msgpack.sh
- components/core/tools/scripts/lib_install/spdlog.sh
- components/core/tools/scripts/lib_install/ubuntu-bionic/install-packages-from-source.sh
- components/core/tools/scripts/lib_install/ubuntu-focal/install-packages-from-source.sh
- components/core/tools/scripts/lib_install/zstandard.sh
None.
Hey there, I've added several tweaks to fix errors when building `clp-core` on macOS.
Tested on macOS.
> Minor tweaks to fix setup on macOS

- components/core/src/ffi/encoding_methods.hpp
- components/core/src/ffi/ir_stream/encoding_methods.cpp
#109
The IR encoding of logtypes mistakenly only escaped variable placeholders. This is an overoptimization that the existing decoders don't expect. This PR fixes it.
Followed the reproduction steps in #109 and verified that backslashes were no longer gobbled up. Unit tests will cover this case once we have support for IR decoding in this repo.
> ffi: Escape escape characters when encoding the logtype for IR streams (fixes #109).

- components/core/src/clp/FileCompressor.cpp
- tools/docker-images/clp-execution-base-focal/setup-scripts/install-prebuilt-packages.sh
https://github.com/y-scope/clp/issues/113
Added Zstd to clp-execution image so libarchive can decompress zstd input
Built the image locally and modified a package to use the local image. Confirmed that zstd files can be compressed by the package.
> Install zstd on execution image for libarchive and update error message

- components/core/CMakeLists.txt
- components/core/src/ffi/ir_stream/decoding_methods.cpp
- components/core/src/ffi/ir_stream/decoding_methods.hpp
- components/core/src/ffi/ir_stream/protocol_constants.hpp
- components/core/tests/test-ir-encoding_methods.cpp
- components/core/tests/test-ir_encoding_methods.cpp
Added decoding support to ffi library.
Added Unit-tests for both 8-bytes and 4-bytes encoding.
> Support decoding IR in ffi::clp 

- components/core/src/ffi/encoding_methods.hpp
- components/core/src/ffi/ir_stream/decoding_methods.cpp
- components/core/tests/test-ir_encoding_methods.cpp
N/A
Let the ir decoder use a temporary version of decode message that properly handles escaped placeholder.
Updated the unit test to cover escaped placeholder in the logtype
> Add temporary decode_message for ir_decoder to handle escaped placehold in the logtype

- components/core/src/Defs.h
- components/core/src/EncodedVariableInterpreter.cpp
- components/core/src/EncodedVariableInterpreter.hpp
- components/core/src/Grep.cpp
- components/core/src/LogTypeDictionaryEntry.cpp
- components/core/src/LogTypeDictionaryEntry.hpp
- components/core/src/compressor_frontend/Constants.hpp
- components/core/src/compressor_frontend/LALR1Parser.tpp
- components/core/src/compressor_frontend/utils.cpp
- components/core/src/streaming_archive/Constants.hpp
- components/core/src/streaming_archive/writer/Archive.cpp
- components/core/src/utils/make_dictionaries_readable/README.md
- components/core/src/utils/make_dictionaries_readable/make-dictionaries-readable.cpp
- components/core/tests/test-EncodedVariableInterpreter.cpp
- components/core/tests/test-encoding_methods.cpp
Use IR format for CLP message encoding and floating number
Compression ratio delta:
hadoop-24hrs. +0.5%
hadoop-30gb. < -0.01%
openstacks-24hr. -0.2%
spark. -0.3%
var-logs. -2%
> Aligns variable placeholder and float encoding with IR format specification

- components/core/src/ffi/ir_stream/encoding_methods.cpp
- components/core/src/ffi/ir_stream/encoding_methods.hpp
Adding two 4-byte encoding methods, which separate message encoding and timestamp encoding. The Python logging library needs to encode messages separately in some cases. This PR is to accommodate Python logging library needs without breaking existing functionalities.
Tested with Python logging libraries and had the correctness verified.
> Additional 4-byte encoding methods

- components/core/src/ffi/ir_stream/decoding_methods.cpp
- components/core/src/ffi/ir_stream/decoding_methods.hpp
- components/core/src/type_utils.hpp
- components/core/tests/test-ir_encoding_methods.cpp
The metadata in a preamble may be encoding in various formats (e.g. json) with sparse fields as needed by individual use cases. Performing the parsing and validation of this metadata in the ffi layer adds unnecessary complexity and constraints to the metadata as the ffi code must handle all use cases.
This PR changes `decode_preamble` to return the position, size, and type tag of the metadata to the upper layer. This allows the user of the ffi decide how they should parse and validate the metadata. This change also unifies `decode_preamble` for four and eight byte encoding, as there is no difference between their behaviour any more.
Adjusted preamble decoding unit tests. All [ffi] tagged tests passing.
> ffi: Return metadata position, size, and type from decode_preamble for upper layer to parse.

- components/core/src/ffi/encoding_methods.tpp
- components/core/tests/test-encoding_methods.cpp
- components/core/tools/scripts/lib_install/macos-12/install-all.sh
`decode_float_var` assumed all eight-byte encoded floats given as input would be valid, but in practice, this is not true if the encoded data was corrupted. This PR adds handling for such values.
* Added new unit tests and validated all unit tests passed.
> ffi: Handle invalid encoded floats in decode_float_var

- components/core/src/ffi/encoding_methods.hpp
- components/core/src/ffi/encoding_methods.tpp
- components/core/tests/test-encoding_methods.cpp
#125 was flawed in that it didn't consider all possible values of the properties that are used to create an encoded float. This PR attempts to add tests for all values of those properties and handle any unhandled inputs.
Added unit tests and validated all unit tests pass.
> ffi: Handle more invalid encoded floats in decode_float_var

- components/core/CMakeLists.txt
- components/core/src/GlobalMetadataDBConfig.cpp
- components/core/src/SQLiteDB.hpp
- components/core/src/SQLitePreparedStatement.hpp
- components/core/src/TimestampPattern.cpp
- components/core/src/ffi/ir_stream/encoding_methods.cpp
- components/core/src/streaming_archive/writer/Archive.cpp
- components/core/tests/test-EncodedVariableInterpreter.cpp
- components/core/tests/test-Grep.cpp
- components/core/tests/test-ParserWithUserSchema.cpp
- components/core/tests/test-Segment.cpp
- components/core/tests/test-Stopwatch.cpp
- components/core/tests/test-StreamingCompression.cpp
- components/core/tests/test-TimestampPattern.cpp
- components/core/tests/test-Utils.cpp
- components/core/tests/test-encoding_methods.cpp
- components/core/tests/test-ir_encoding_methods.cpp
- components/core/tests/test-main.cpp
- components/core/tests/test-query_methods.cpp
- components/core/tests/test-string_utils.cpp
To improve portability and avoid dependency on file structure include directives of submodules are switched from relative paths to using include paths.
All unit tests passing.
> Change include directives of submodules to use include path rather than relative path.

- components/core/tools/scripts/deps-download/download-dep.py
`download-depy.py` was failing on Ubuntu Bionic and CentOS 7 because the default Python version installed on those OSes doesn't support passing a path-like object to `unpack_archive`. This PR goes back to passing a string in instead of a path-like object.
Verified `download-dep.py` succeeds on Ubuntu Bionic and CentOS 7.
> download-dep: Use correct parameter type to support old Python versions.

- components/clp-py-utils/clp_py_utils/initialize-clp-metadata-db.py
- components/core/CMakeLists.txt
- components/core/src/GlobalMetadataDB.hpp
- components/core/src/GlobalMySQLMetadataDB.cpp
- components/core/src/GlobalMySQLMetadataDB.hpp
- components/core/src/GlobalSQLiteMetadataDB.cpp
- components/core/src/GlobalSQLiteMetadataDB.hpp
- components/core/src/clg/clg.cpp
- components/core/src/clp/decompression.cpp
- components/core/src/streaming_archive/ArchiveMetadata.cpp
- components/core/src/streaming_archive/ArchiveMetadata.hpp
- components/core/src/streaming_archive/Constants.hpp
- components/core/src/streaming_archive/reader/Archive.cpp
- components/core/src/streaming_archive/reader/Archive.hpp
- components/core/src/streaming_archive/writer/Archive.cpp
- components/core/src/streaming_archive/writer/Archive.hpp
- components/core/src/streaming_archive/writer/Segment.cpp
- components/core/src/streaming_archive/writer/Segment.hpp
- components/core/tools/scripts/db/init-db.py
When using MySQL as metadata db, only retrieve archive directories that have logs in the given search time window. This will improve search performance.
Functional tests on Ubuntu bionic.
> Retrieve archives that have logs in the given search time window

- components/core/src/ffi/ir_stream/encoding_methods.cpp
Quick fix so that the library component of clp-ffi-go can build with `-Werror`.
All unit tests passing, both release and debug.
> FFI: Comment out unused parameter to allow ffi-go to build with werror

- components/core/src/ffi/encoding_methods.cpp
- components/core/src/ffi/encoding_methods.hpp
- components/core/src/ffi/encoding_methods.tpp
- components/core/src/ffi/ir_stream/byteswap.hpp
- components/core/src/ffi/ir_stream/decoding_methods.cpp
- components/core/src/ffi/ir_stream/decoding_methods.hpp
- components/core/src/ffi/ir_stream/encoding_methods.cpp
- components/core/src/ffi/ir_stream/encoding_methods.hpp
- components/core/src/ffi/ir_stream/protocol_constants.hpp
- components/core/src/ffi/search/CompositeWildcardToken.cpp
- components/core/src/ffi/search/CompositeWildcardToken.hpp
- components/core/src/ffi/search/ExactVariableToken.cpp
- components/core/src/ffi/search/ExactVariableToken.hpp
- components/core/src/ffi/search/QueryMethodFailed.hpp
- components/core/src/ffi/search/QueryToken.hpp
- components/core/src/ffi/search/QueryWildcard.cpp
- components/core/src/ffi/search/QueryWildcard.hpp
- components/core/src/ffi/search/Subquery.cpp
- components/core/src/ffi/search/Subquery.hpp
- components/core/src/ffi/search/WildcardToken.cpp
- components/core/src/ffi/search/WildcardToken.hpp
- components/core/src/ffi/search/query_methods.cpp
- components/core/src/ffi/search/query_methods.hpp
Applies clang format to the ffi sub-directories and also adjusts comments to be <= 80.
Removes header group comments (e.g. // Project headers) now that clang-format organizes them.
All unit tests passing.
> Apply clang-format to ffi

- components/core/src/Defs.h
- components/core/src/LogTypeDictionaryEntry.cpp
- components/core/src/LogTypeDictionaryEntry.hpp
- components/core/src/LogTypeDictionaryWriter.cpp
- components/core/src/streaming_archive/Constants.hpp
Verbosity is a required field for a log type entry since the majority of unstructured logs have such information. However, we don't actually use this field. Besides, in the case of semi-structured logs, this information is typically stored in a dedicated field (e.g., `level`), and the actual log text does not include it. Removing this field saves ingestion time and storage space.
* Validated compression/decompression/search continues to work.
* Validated unit tests still pass.
> Remove verbosity field for a log type entry

- components/core/src/streaming_archive/writer/Archive.hpp
-Added required headers for newer (GCC/G++)/Ubuntu versions in Archive.hpp
- GCC version 12.3.0
- Ubuntu 23.04
- path: core/src/streaming_archive/writer/Archive.hpp
Ran with all 49 executable and unit tests in CLP
> Library Inclusion in Archive.hpp

- components/core/src/string_utils.cpp
- components/core/src/string_utils.hpp
- components/core/src/string_utils.tpp
Applies clang format to the string_utils files and also adjusts comments to be <= 80.
Removes header group comments (e.g. // Project headers) now that clang-format organizes them.
unit tests passing
> Apply clang-format to string_utils.*pp

- components/core/src/string_utils.cpp
- components/core/src/string_utils.hpp
Removed dead code in string_utils to fix compiler warnings, alllowing FFI libraries (and one day clp...) to build with -Werror.
unit tests passing
> Remove dead code and unused parameter from string_utils to build with -Werror

- components/core/src/ffi/encoding_methods.hpp
- components/core/src/ffi/encoding_methods.tpp
Building FFI libraries with clang 16 with `-Werror` will fail due to a signed-unsigned comparison in the wildcard query matching. Changing the encoded variable array length to `size_t` resolves this and is generally the expected type for container `.size()`  calls.
Clp builds, unit tests pass, also works as expected with go ffi library.
> [ffi] Fix clang warning by changing encoded_vars_length to size_t from int in wildcard query match.

- .gitmodules
In #152, we mistakenly used an ssh URL for boost-outcome instead of https. This fixes it.
Validated that the submodule can be downloaded with the new URL.
> Switch boost-outcome's repo URL from ssh to https.

- components/core/src/streaming_archive/MetadataDB.cpp
- components/core/src/streaming_archive/reader/Archive.cpp
There are two minor bugs found in the current metadata database, and this PR is to address these two bugs:
1. The archive reader should raise an exception if the metadata db is not found in the archive instead of silencing the error.
2. After the metadata data base is successfully opened, the `m_is_open` flag should be set to true.
> Fix archive metadata db related bugs

- components/core/src/TraceableException.hpp
Without `SOURCE_PATH_SIZE` defined compilation fails as `__FILENAME__` (a relative path version of `__FILE__`) fails to be defined. However, a relative file path should not be a hard requirement for building/running CLP. Therefore, we default back to `__FILE__` when `SOURCE_PATH_SIZE` is not defined.
All unit tests passing with or without `SOURCE_PATH_SIZE` defined.
> Default __FILENAME__ to __FILE__ when the source path size has not been defined.

- components/core/src/clp/FileCompressor.cpp
Missed a parameter in the log statement introduced in 03cedcdf391ddbe409196a627dc8e0a128941207. This PR fixes it.
* Created an IR file with only a magic number.
* Attempted to compress it with clp and validated that it printed the error log *with* the path.
> Add missing parameter to log statement.

- components/core/src/ffi/ir_stream/decoding_methods.cpp
- components/core/src/ffi/ir_stream/decoding_methods.hpp
- components/core/src/ffi/ir_stream/encoding_methods.cpp
- components/core/src/ffi/ir_stream/protocol_constants.hpp
- components/core/src/ir/LogEventDeserializer.cpp
- components/core/tests/test-ir_encoding_methods.cpp
The current IR encoding protocol doesn't support 8-byte timestamp delta encoding. This means the current four-byte encoding IR stream cannot contain a timestamp delta of more than +/- 24.86 days. This PR resolves this problem by introducing an 8-byte timestamp delta encoding.
The protocol version number is bumped to "v0.0.1". As a result, the version of the decoder must have been up-to-date to decode an 8-byte encoded timestamp delta properly.
To validate the version, a validation function is added to check whether the built protocol version number is greater or equal to the input protocol version number. The current version validation relies on the SemVar [https://semver.org/#backusnaur-form-grammar-for-valid-semver-versions](url) convention.
- Added unit tests to cover the timestamp …
> Add support for the 8-byte long timestamp delta encoding

- components/core/src/ffi/encoding_methods.hpp
- components/core/src/ffi/encoding_methods.inc
- components/core/tests/test-encoding_methods.cpp
https://github.com/y-scope/clp/issues/172
The `encode_float_properties` method doesn't correctly handle cases where the given input exceeds the representable range for four-byte encoding. When it happens, it will return `false` which is interpreted as encoded `.0`. This PR fixes this bug by moving the range check to the `encode_float_string` method to ensure the input to the `encode_float_properties` is always in-bound.
1. Passed all the existing unit tests.
2. Added unit test cases to cover the out-of-range scenarios.
3. Validated on the incorrect user logs to ensure it can now generate the correct output.
> Fix four-byte float encoding methods to properly handle cases where the input float exceeds the representable range.

- .github/workflows/clp-core-build-macos.yaml
- .github/workflows/clp-core-build.yaml
- .github/workflows/clp-execution-image-build.yaml
I mistakenly removed the `pull_request` workflow trigger in #175 thinking that `push` was a superset of `pull_request`. This PR adds the trigger back.
* Added the `pull_request` workflow trigger to the main branch of my fork.
* Tested a PR from a different repo to my fork and validated that the workflows were triggered.
> Add pull_request GH workflow trigger to all workflows.

- components/core/CMakeLists.txt
- components/core/src/networking/SocketOperationFailed.cpp
- components/core/src/networking/SocketOperationFailed.hpp
- components/core/src/networking/socket_utils.cpp
- components/core/src/networking/socket_utils.hpp
* Applied clang-format to all files in the `networking` namespace.
* Deleted unnecessary files.
* Removed include grouping comments since clang-format organizes them.
* Builds successfully
> Apply clang-format to networking namespace.

- components/core/tools/scripts/deps-download/download-all.sh
- components/core/tools/scripts/deps-download/log-surgeon.json
We added log-surgeon as a submodule in #131 but didn't add it to the dependencies that can be downloaded when git is unavailable (e.g., when building CLP from a release where the `.git` directory doesn't exist). This PR adds it.
Validated that log-surgeon was downloaded when building `core` from a source-only (no `.git` directory) release.
> Add log-surgeon to dependencies downloadable without git.

- .github/workflows/clp-core-lint.yaml
- components/core/src/clp/clp.cpp
Adds a workflow to validate that clang-format was applied to all of core's source files.
NOTE: There is an argument to be made that failure of this workflow should prevent the build workflows from running, but we have multiple build jobs and creating dependencies between workflows is complicated and not well supported.
Validated that the workflow runs on changes to source files and that incorrectly formatted files cause the workflow to fail.
> Add workflow to validate clang-format was applied to core's sources

- components/core/tools/scripts/lib_install/ubuntu-focal/install-packages-from-source.sh
- components/core/tools/scripts/lib_install/ubuntu-focal/install-prebuilt-packages.sh
In the script to install `core`'s dependencies on Ubuntu Focal, we're using a prebuilt package for the MariaDB C connector; but it's downloaded directly from mariadb.com rather than the default apt repositories. If a user already has the package from apt installed, the prebuilt package used in the script would unnecessarily replace their existing one.
This PR changes the Focal install script to use the apt package instead.
Validated the core build workflows passed.
> Use apt package for MariaDB C connector on Ubuntu Focal.

- .github/actions/clp-core-build-containers/action.yaml
The current workflow will use the GitHub id+repository name to generate an ID to name the build container. However, if the user's GitHub ID contains uppercase letters, the docker would fail to initiate (this was uncovered when I tried to run CLP workflow in my forked repo). This PR fixes this problem by introducing an additional step to lowercase the repository name.
1. GitHub actions all passed in the forked repo.
2. Manually checked the generated docker ID doesn't contain uppercase letters (LinZhihao-723 -> linzhihao-723):
> Convert repository names to lowercase before using them in docker image names.

- components/core/src/clp/FileDecompressor.cpp
- components/core/src/clp/FileDecompressor.hpp
- components/core/src/clp/decompression.cpp
- components/core/src/streaming_archive/reader/Archive.cpp
- components/core/src/streaming_archive/reader/Archive.hpp
- components/core/src/streaming_archive/reader/File.cpp
- components/core/src/streaming_archive/reader/File.hpp
The current decompression code has unnecessary calls of getting the original file path from the DB file iterator during the decompression. This PR cleans up all the unnecessary calls. In addition, it turned to be confusing when I first saw them since the iterator was passed into the decompressor without `const` decoration. This misled me to consider whether the iterator was modified through the decompression process. To clarify the behavior, `const` is added all the way down from the archive reader to the file reader to indicate it is immutable through the file decompression.
> Remove unnecessary calls of getting the original path from the file iterator.

- components/core/src/ffi/ir_stream/decoding_methods.cpp
- components/core/src/ffi/ir_stream/decoding_methods.hpp
- components/core/src/ffi/ir_stream/encoding_methods.cpp
- components/core/src/ffi/ir_stream/encoding_methods.hpp
- components/core/src/ir/LogEventDeserializer.cpp
- components/core/tests/test-ir_encoding_methods.cpp
* Change encode/decode to serialize/deserialize.
* Change "message" to "log event" where appropriate.
The IR stream methods in `ffi::ir_stream` use names like `encode_message` which is confusing when (1) we already have `encode_message` in the `ffi` namespace and (2) the IR stream methods are really serializing/deserializing rather than encoding/decoding. In addition, in several places we use `message` when we really mean `log event`. This PR resolves both issues.
Validated unit tests pass.
> Rename IR-stream related methods:

- components/core/src/Grep.cpp
- components/core/src/Grep.hpp
- components/core/src/Query.cpp
- components/core/src/Query.hpp
- components/core/src/clg/clg.cpp
- components/core/src/clo/clo.cpp
Previously, when we push new elements into `m_relevant_sub_queries`, we use 
`m_relevant_sub_queries.push_back(&m_sub_queries.back());`. However, `m_sub_queries` is a vector and the memory is dynamically allocated. Upon resizing, it may use new addresses and pointers stored in `m_relevant_sub_queries` are no longer valid.
Passed unit test and clang-format check. Also ran queries which cover the affected code and got expected results
> Fix a memory bug related to m_relevant_sub_queries

- components/core/src/Grep.cpp
- components/core/src/Query.cpp
- components/core/src/Query.hpp
The `Query` class had setter methods for its members but they were only used in one method (`Grep::process_raw_query`). This PR simplifies `Query` so it takes its parameters in the constructor rather than through setters.
* Compressed some logs using the parsing heuristics.
* Validated a query returned the same results as grep.
* Compressed some logs using the schema-based parser.
* Repeated the validation step.
> Initialize the Query class through its constructor rather than separate setter methods.

- .github/workflows/clp-core-lint.yaml
- components/core/.gitignore
- components/core/Taskfile.yml
- components/core/src/Query.hpp
Linting can now be performed by running `task lint` (assuming the user has `task` installed).
For now, this remains undocumented; we could document it as a contribution guideline in the README but since our other guidelines are not documented, it would be confusing for new contributors why we have one guideline documented but not others. We will document the others soon.
* Validated that linting worked through the lint workflow (which now calls the lint task).
* Validated that linting worked locally.
> Add taskfile to simplify linting the core component.

- README.md
The current README contains descriptions of the docker images published to [GitHub packages](https://github.com/features/packages) but it can be confusing for a user who doesn't know what GitHub packages is.
This PR improves the README as follows:
* Provides more context about GitHub packages.
* Provides the full image name so that users can easily copy it without going through multiple pages to get it.
* Refactors the text to be more readable.
> Improve descriptions of the artifacts published to GitHub packages.

- components/clp-package-utils/clp_package_utils/scripts/native/search.py
- components/clp-package-utils/clp_package_utils/scripts/search.py
- components/job-orchestration/job_orchestration/executor/search_task.py
- components/job-orchestration/job_orchestration/job_config.py
The CLP package doesn't currently support filtering by timestamp (although the `clg` binary does). We do have support in the package on the [v0.5-prototype](https://github.com/y-scope/clp/tree/v0.5-prototype) branch, but that's still being merged to main. Since a user asked about the feature in #191, this PR adds support for it as a holdover until we finish merging v0.5-prototype.
* Compressed the [hive-24hr](https://zenodo.org/records/7094921#.Y5JbH33MKHs) dataset with the package.
* Validated that a search for a begin-timestamp outside the range of the archives returns no results:
```shell
sbin/search.sh --begin-time 1427169541159  " INFO "
```
* Also validated that no search tasks were generated in the database.
* Validated that a search for a begin-timestamp one less than the one …
> Add support for filtering by timestamp to the CLP package.

- components/core/README.md
We added [log-surgeon](https://github.com/y-scope/log-surgeon) as a submodule in #131 but didn't add it as a source dependency in CLP core's README.
> Add log-surgeon source-dependency to README.

- .github/workflows/clp-core-lint.yaml
- .yamllint.yml
- components/core/.clang-format
- components/core/Taskfile.yml
- components/core/src/EncodedVariableInterpreter.cpp
- components/core/src/streaming_archive/writer/Segment.cpp
- Add Taskfile rule to apply lint fixes.
- Add .clang-format to list of files for yamllint to check.
- Fix .clang-format's yamllint violations.
- Fix .clang-format rule error.
- Fix .clang-format regex for C standard library headers.
- Fix venv generation so `activate` remains valid.
This PR mainly adds a convenient rule to apply core's lint fixes and reformats the `.clang-format` file.
* Validated the fix and check rules work.
* Validated the lint workflow still works.
> Linting improvements for core component:

- components/core/src/streaming_archive/reader/File.cpp
- components/core/tests/test-Segment.cpp
- components/core/tests/test-Utils.cpp
- components/core/tests/test-string_utils.cpp
The [style guide](https://google.github.io/styleguide/cppguide.html#Namespaces) prohibits the use of `using` declarations to include all symbols from a namespace.
* Built successfully.
* Unit tests pass.
> Replace instances of using namespace with using <symbol>.

- components/core/CMakeLists.txt
- components/core/src/clp/GlobalMetadataDB.hpp
- components/core/src/clp/GlobalMetadataDBConfig.cpp
- components/core/src/clp/GlobalMetadataDBConfig.hpp
- components/core/src/clp/GlobalMySQLMetadataDB.cpp
- components/core/src/clp/GlobalMySQLMetadataDB.hpp
- components/core/src/clp/GlobalSQLiteMetadataDB.cpp
- components/core/src/clp/GlobalSQLiteMetadataDB.hpp
- components/core/src/clp/clg/CMakeLists.txt
- components/core/src/clp/clg/CommandLineArguments.hpp
- components/core/src/clp/clg/clg.cpp
- components/core/src/clp/clp/CMakeLists.txt
- components/core/src/clp/clp/CommandLineArguments.hpp
- components/core/src/clp/clp/compression.cpp
- components/core/src/clp/clp/decompression.cpp
- components/core/src/streaming_archive/writer/Archive.hpp
- components/core/tests/test-ParserWithUserSchema.cpp
This PR moves the sources for CLP's global metadata DB classes into the `clp` namespace. Ideally, we'd turn this into a library but we need to clean-up its dependencies first, so we're deferring the library to another PR.
* Validated unit tests pass.
* Validated a search `"DESERIALIZE_ERRORS"` returns the same (after sorting) results as `grep`.
> Move global metadata DB sources into the clp namespace.

- components/core/src/clp/clo/CMakeLists.txt
- components/core/src/clp/clo/ControllerMonitoringThread.cpp
- components/core/src/clp/clo/clo.cpp
- components/core/src/clp/networking/SocketOperationFailed.hpp
- components/core/src/clp/networking/socket_utils.cpp
- components/core/src/clp/networking/socket_utils.hpp
This PR moves the networking sources into the `clp` namespace.
* Validated unit tests pass.
* Validated a search `"DESERIALIZE_ERRORS"` returns the same (after sorting) results as `grep`.
> Move networking sources into the clp namespace.

- components/core/.clang-format
- components/core/src/ffi/ir_stream/decoding_methods.cpp
- components/core/src/ffi/ir_stream/decoding_methods.hpp
- components/core/src/ffi/ir_stream/encoding_methods.cpp
- components/core/src/ffi/ir_stream/encoding_methods.hpp
- components/core/src/ffi/ir_stream/protocol_constants.hpp
- components/core/src/streaming_archive/Constants.hpp
- components/core/src/streaming_archive/reader/Archive.cpp
- components/core/src/streaming_archive/reader/Archive.hpp
- components/core/src/streaming_archive/reader/Message.cpp
- components/core/src/streaming_archive/reader/Message.hpp
- components/core/src/streaming_archive/reader/Segment.cpp
- components/core/src/streaming_archive/reader/Segment.hpp
- components/core/src/streaming_archive/reader/SegmentManager.cpp
- components/core/src/streaming_archive/reader/SegmentManager.hpp
- components/core/src/streaming_archive/writer/Archive.hpp
- components/core/src/streaming_archive/writer/File.cpp
- components/core/src/streaming_archive/writer/File.hpp
- components/core/src/streaming_archive/writer/Segment.cpp
- components/core/src/streaming_archive/writer/Segment.hpp
- components/core/src/streaming_compression/passthrough/Compressor.cpp
- components/core/src/streaming_compression/passthrough/Compressor.hpp
- components/core/src/streaming_compression/passthrough/Decompressor.cpp
- components/core/src/streaming_compression/passthrough/Decompressor.hpp
- components/core/src/streaming_compression/zstd/Compressor.cpp
- components/core/src/streaming_compression/zstd/Compressor.hpp
- components/core/src/streaming_compression/zstd/Constants.hpp
- components/core/src/streaming_compression/zstd/Decompressor.cpp
- components/core/src/streaming_compression/zstd/Decompressor.hpp
The current clang-format config formats a nested namespace with a joined name (`namespace a::b`) with no indentation but a nested namespace with separated names (`namespace a { namespace b {`) is formatted with indentation. This leads to tedious indentation changes (for the reviewer) when moving code into/out of a namespace.
This PR:
* Joins nested namespaces of the form `namespace a { namespace b { ... }}` into `namespace a::b { ... }`.
* Changes the clang-format config to not indent inner namespaces.
* Built successfully.
* Unit tests pass.
> Join nested namespace names to reduce indentation; Don't indent inner namespaces.

- components/core/CMakeLists.txt
- components/core/src/clp/EncodedVariableInterpreter.cpp
- components/core/src/clp/EncodedVariableInterpreter.hpp
- components/core/src/clp/Grep.cpp
- components/core/src/clp/Grep.hpp
- components/core/src/clp/LogSurgeonReader.cpp
- components/core/src/clp/LogSurgeonReader.hpp
- components/core/src/clp/clg/CMakeLists.txt
- components/core/src/clp/clg/clg.cpp
- components/core/src/clp/clo/CMakeLists.txt
- components/core/src/clp/clo/clo.cpp
- components/core/src/clp/clp/CMakeLists.txt
- components/core/src/clp/clp/FileCompressor.cpp
- components/core/src/clp/streaming_archive/reader/Archive.cpp
- components/core/src/clp/streaming_archive/reader/File.cpp
- components/core/src/clp/streaming_archive/writer/Archive.cpp
- components/core/src/clp/streaming_archive/writer/File.cpp
- components/core/tests/test-EncodedVariableInterpreter.cpp
- components/core/tests/test-Grep.cpp
- components/core/tests/test-ParserWithUserSchema.cpp
This PR moves the `EncodedVariableInterpreter`, `Grep`, and `LogSurgeonReader` sources into the `clp` namespace.
* Validated unit tests pass.
* Validated a search `"DESERIALIZE_ERRORS"` returns the same (after sorting) results as `grep`.
> Move EncodedVariableInterpreter, Grep, and LogSurgeonReader sources into the clp namespace.

- components/clp-package-utils/clp_package_utils/scripts/start_clp.py
- components/package-template/src/README.md
#179 moved the package scripts into a Python package but we missed updating some references to the scripts in the code (when the package tries to stop itself on error when starting up) and the readme.
* Validated that the package could be started and stopped successfully.
* Validated that the package can successfully stop itself when it encounters an error during start up.
> Fix incomplete renaming of package scripts.

- README.md
- components/core/tools/docker-images/clp-core-ubuntu-focal/Dockerfile
- docs/core/clp-core-container.md
This PR adds `clp-s` to ` clp-core-x86-ubuntu-focal` and adds a README for how to use it. This PR also removes `clo` from the container since it is not used outside the package.
* Built ` clp-core-x86-ubuntu-focal ` locally and validated that it contained `clp-s`.
* Validated that, following the README, it was possible to use `clg`, `clp` and `clp-s` to compression, decompress, and search logs.
> Add clp-s to the container image containing core's binaries; Add docs for using the container image.

- .github/workflows/clp-core-build.yaml
The filter in `.github/workflows/clp-core-build.yaml` for deciding when to build and push the container images did not include the `Dockerfile` for `clp-core-x86-ubuntu-focal`, so #225 did not end up building and pushing the new container image to ghcr.io. This PR adds it to the filter.
Strictly speaking, when `components/core/tools/docker-images/clp-core-ubuntu-focal/Dockerfile` changes, we don't need to build and push `clp-core-dependencies-x86-ubuntu-focal`, but separating the filters for the two images is more work than it's worth.
* Merged this PR to `main` in my fork.
* Pushed a change to `components/core/tools/docker-images/clp-core-ubuntu-focal/Dockerfile` in my fork and validated that the image filter was true.
> Add missing file to changes relevant for rebuilding container image.

- components/core/tools/scripts/lib_install/centos7.4/install-all.sh
- components/core/tools/scripts/lib_install/centos7.4/install-packages-from-source.sh
- components/core/tools/scripts/lib_install/centos7.4/install-prebuilt-packages.sh
- components/core/tools/scripts/lib_install/macos-12/install-all.sh
- components/core/tools/scripts/lib_install/mongoc.sh
- components/core/tools/scripts/lib_install/mongocxx.sh
- components/core/tools/scripts/lib_install/ubuntu-focal/install-all.sh
- components/core/tools/scripts/lib_install/ubuntu-focal/install-packages-from-source.sh
- components/core/tools/scripts/lib_install/ubuntu-focal/install-prebuilt-packages.sh
- components/core/tools/scripts/lib_install/ubuntu-jammy/install-all.sh
- components/core/tools/scripts/lib_install/ubuntu-jammy/install-packages-from-source.sh
- components/core/tools/scripts/lib_install/ubuntu-jammy/install-prebuilt-packages.sh
- tools/docker-images/clp-execution-base-focal/setup-scripts/install-prebuilt-packages.sh
- Error on failure to install any package into the container image.
- Don't use an empty array as a command (for older Bash versions).
Recent failures to install packages in the CentOS container were not being caught until we tried to build CLP in the container since the script which calls the package install script didn't exit on error. In addition, mongoc and mongocxx were failing to install in the CentOS container since it uses an older version of bash which doesn't support expanding an empty array (it treats it as an unbound variable).
This PR adds error checks in the scripts which call the package install scripts and fixes the mongoc/cxx install scripts to support the older version of bash.
* Validated that the mongo/cxx install failures were caught when the install scripts were …
> Container image build fixes:

- Taskfile.yml
- docs/Building.md
- Use a file to detect successful venv/package.
- Use a venv when installing components into the package.
This PR fixes three issues:
1. When the package fails to build (e.g., because python3-venv was not installed), the Taskfile doesn't detect that the venv/package creation was unsuccessful; this is because we use the presence of the venv/package directory to determine whether the task was already completed.
* This PR changes the Taskfile to create a file at the end of each venv and package task, and then we use this file to determine whether the task was completed successfully.
2. Attempting to build the package in an environment with an older version of `poetry` (compared to the one used to build the components) already installed caused the build to fail when installing the components …
> Package build fixes:

- Taskfile.yml
The package build wasn't detecting changes within sub-directories of a directory tracked using the glob `dir/**`. This PR uses the glob `dir/**/*` to do so.
This PR also sets up the `core-submodules` task to only rerun on changes to the configured submodules.
* Built the package using `task`.
* Reran `task` to ensure no task reran.
* Changed a file in `components/clp-package-utils/clp_package_utils/scripts/`.
* Reran `task` and validated that the package task reran.
* Changed a file in `components/clp-package-utils/clp_package_utils/`.
* Reran `task` and validated that the package task reran.
> Package build: Track changes in sub-directories.

- components/core/src/clp/Defs.h
- components/core/src/clp/PageAllocatedVector.hpp
- components/core/src/clp/streaming_archive/writer/Archive.cpp
- components/core/src/clp/streaming_archive/writer/Archive.hpp
This PR cleans up unused and obsolete definitions from Defs.h.
* Validated unit tests pass.
* Validated a search `"DESERIALIZE_ERRORS"` returns the same (after sorting) results as `grep`.
> Clean up Defs.h

- components/core/src/clp_s/CMakeLists.txt
- components/core/src/clp_s/CommandLineArguments.cpp
- components/core/src/clp_s/CommandLineArguments.hpp
- components/core/src/clp_s/Defs.hpp
- components/core/src/clp_s/clp-s.cpp
- components/core/src/clp_s/search/Output.cpp
- components/core/src/clp_s/search/Output.hpp
- components/core/src/clp_s/search/OutputHandler.cpp
- components/core/src/clp_s/search/OutputHandler.hpp
#223 
#223 added supports for sending query results to results_cache (MongoDB) for clp package. This PR added MongoDB output support for clp-s binary. We will integrate clp-s with the package and allow user to choose between clp and clp-s in the upcoming PR.
+ Successfully compiled the source code
+ Tested search with output to both stdout and MongoDB
> Add MongoDB output support for clp-s search

- components/core/src/clp/streaming_archive/writer/File.cpp
- components/core/src/clp/streaming_archive/writer/utils.cpp
fixes issue #167 
**Summary of issue:**
When compressing/decompressing Loghub dataset, one file without timestamps had logs out-of-order when compared to original dataset. Out-of-order logs were a result of compressing some logs to the incorrect segment. Specifically logs were being compressed into `m_segment_for_files_with_timestamp` instead of `m_segment_for_files_without_timestamp`.
For large files, the [split_file function][1] is called, which then calls [change_ts_pattern function][2], where there is a bug. The function is meant to pass timestamps from the first chunk of the file, to the second chunk, but if there is no timestamp, it passes an unintialized timestamp object. This is the bug, it should pass nothing for files without timestamps. Clp incorrectly believes the …
> Don't set timestamp format when splitting a timestamp-less file (fixes #167).

- components/clp-package-utils/clp_package_utils/scripts/start_clp.py
A locally built package fails to start the worker because the shebang in the celery script points to Python in the venv used to build the package (which is not inside the execution container).
There doesn't seem to an option to make an installed Python package ignore or use a different Python path from the one it was installed with so, for now, this PR works around the issue by calling `bin/celery` through Python rather than executing the script directly.
* Validated the workers start up successfully.
* Validated a search "DESERIALIZE_ERRORS" returns the same (after sorting) results as grep.
> Start celery through Python to work around incorrect Python shebang.

- components/clp-package-utils/clp_package_utils/scripts/start_clp.py
- components/clp-py-utils/clp_py_utils/clp_config.py
- components/clp-py-utils/pyproject.toml
- components/job-orchestration/job_orchestration/executor/search/fs_search_task.py
- components/job-orchestration/pyproject.toml
- components/package-template/src/etc/clp-config.yml
Add package mode configuration option for the clp package. Currently the only valid mode is "clp", but "clp-s" will also become valid once we finishing adding support.
This change pulls in the StrEnum package to allow us to easily enumerate all of the valid modes. We can't use python's built in string enums because they're only available in python 3.11+.
- Verified that compression and search flow work as expected
- Verified that invalid modes will cause validation errors
> Add package mode as clp package configuration parameter

- components/core/src/clp_s/SchemaReader.hpp
- components/core/src/clp_s/search/Output.cpp
- components/core/src/clp_s/search/Output.hpp
- docs/core/clp-structured.md
For precise search within an array nlohmann json is currently being used to parse and scan json arrays.
This PR replaces the nlohmann based implementation with a simdjson based implementation to improve array scan performance.
This PR also updates the clp-s README to better describe the current limitations on array searches.
Compared execution speed with previous implementation and saw ~1.7x speedup on queries on real data.
> Use simdjson for precise array search in clp-s

- components/core/src/clp_s/CMakeLists.txt
- components/core/src/clp_s/CommandLineArguments.cpp
- components/core/src/clp_s/CommandLineArguments.hpp
- components/core/src/clp_s/TimestampDictionaryReader.cpp
- components/core/src/clp_s/TimestampDictionaryReader.hpp
- components/core/src/clp_s/clp-s.cpp
- components/core/src/clp_s/search/AddTimestampConditions.cpp
- components/core/src/clp_s/search/AddTimestampConditions.hpp
- components/core/src/clp_s/search/EvaluateTimestampIndex.cpp
This PR adds the optional --tle TS and --tge TS options to clp-s which specify filtering for records with a timestamp greater than or equal to or less than or equal to a given value respectively.
This filtering is performed by finding the authoritative timestamp column in the timestamp dictionary, and adding filters on that column directly to the search AST as required.
- Validated that specifying an invalid time range (begin > end) prints an error message
- Validated that using tle or tge on an archive with no timestamp key returns no results
- Validated that specifying a timestamp filter with tle/tge will return identical results to specifying the same time filters in the search query
> Add options to clp-s to filter on the authoratative timestamp column specified at ingestion time

- components/core/src/clp_s/ArchiveReader.cpp
- components/core/src/clp_s/ArchiveReader.hpp
- components/core/src/clp_s/ArchiveWriter.cpp
- components/core/src/clp_s/ArchiveWriter.hpp
- components/core/src/clp_s/CMakeLists.txt
- components/core/src/clp_s/CommandLineArguments.cpp
- components/core/src/clp_s/JsonParser.cpp
- components/core/src/clp_s/JsonParser.hpp
- components/core/src/clp_s/ReaderUtils.cpp
- components/core/src/clp_s/ReaderUtils.hpp
- components/core/src/clp_s/Schema.cpp
- components/core/src/clp_s/Schema.hpp
- components/core/src/clp_s/SchemaMap.cpp
- components/core/src/clp_s/SchemaMap.hpp
This PR replaces the in-memory representation of clp-s schemas with a class that wraps std::vector.
This new Schema class allows for schemas to contain a region of nodes ordered by mst node id, followed by a region of unordered nodes. This will be useful if we start supporting more generic parsers for some types of data which need to define their own order, or potentially if we change how we treat arrays.
This implementation still requires all of the node ids within a schema to be unique, though this restriction could be lifted if we make some changes to ParsedRecord and make some changes in Schema Matching.
Besides that, this change improves compression speed by about 10% for some datasets.
- validated that compressed archives are identical for some datasets before and after this change …
> Use a vector instead of a set to represent clp-s schemas

- components/core/src/clp_s/ArchiveWriter.cpp
- components/core/src/clp_s/ColumnWriter.cpp
- components/core/src/clp_s/ColumnWriter.hpp
- components/core/src/clp_s/JsonParser.cpp
- components/core/src/clp_s/JsonParser.hpp
- components/core/src/clp_s/TimestampDictionaryReader.cpp
- components/core/src/clp_s/TimestampDictionaryWriter.cpp
- components/core/src/clp_s/TimestampDictionaryWriter.hpp
- components/core/src/clp_s/TimestampEntry.cpp
- components/core/src/clp_s/TimestampEntry.hpp
- components/core/src/clp_s/clp-s.cpp
This PR fixes the bug of not correctly storing nested timestamp fields. It also adds support for storing column IDs in the timestamp dictionary, which will save effort when extracting timestamps.
+ Built clp-s and compressed part of [mongodb](https://zenodo.org/records/10516285) dataset.
+ Ran query "id: 23285" and checked mongodb documents.
> Fix a bug of nested timestamp fields and store column IDs in the timestamp dictionary

- Taskfile.yml
- components/clp-package-utils/clp_package_utils/scripts/compress.py
- components/clp-package-utils/clp_package_utils/scripts/native/compress.py
- components/clp-py-utils/clp_py_utils/clp_config.py
- components/core/src/clp_s/ArchiveWriter.cpp
- components/core/src/clp_s/ArchiveWriter.hpp
- components/core/src/clp_s/CMakeLists.txt
- components/core/src/clp_s/CommandLineArguments.cpp
- components/core/src/clp_s/CommandLineArguments.hpp
- components/core/src/clp_s/DictionaryWriter.hpp
- components/core/src/clp_s/JsonFileIterator.hpp
- components/core/src/clp_s/JsonParser.cpp
- components/core/src/clp_s/JsonParser.hpp
- components/core/src/clp_s/SchemaMap.cpp
- components/core/src/clp_s/SchemaMap.hpp
- components/core/src/clp_s/SchemaWriter.cpp
- components/core/src/clp_s/SchemaWriter.hpp
- components/core/src/clp_s/TimestampDictionaryWriter.cpp
- components/core/src/clp_s/TimestampDictionaryWriter.hpp
- components/core/src/clp_s/TimestampEntry.cpp
- components/core/src/clp_s/TimestampEntry.hpp
- components/core/src/clp_s/clp-s.cpp
- components/job-orchestration/job_orchestration/executor/compress/fs_compression_task.py
- components/job-orchestration/job_orchestration/executor/search/fs_search_task.py
- components/job-orchestration/job_orchestration/scheduler/job_config.py
Adds support for clp-s as a storage engine in the clp package.
* Add StorageEngine configuration parameter for clp-s
* Add option for clp-s to record archive metadata in MySQL database at compression time
* Change clp-s compression behaviour to create an archive in the directory specified by the user instead of as the archive specified by the user
* Add optional timestamp-key argument to compression jobs
* Ingested data with the clp-s storage engine and timestamp-key argument
* Verified that search using timestamp arguments returns correct results
> Add support for clp-s storage engine in clp package

- tools/docker-images/clp-execution-base-focal/build.sh
- tools/docker-images/clp-execution-base-focal/setup-scripts/install-prebuilt-packages.sh
- tools/docker-images/clp-execution-base-jammy/Dockerfile
- tools/docker-images/clp-execution-base-jammy/build.sh
- tools/docker-images/clp-execution-base-jammy/setup-scripts/install-prebuilt-packages.sh
1. let the naming of the container image to be platform specific
2. Added ubuntu 22.04 build script
Manually confirmed container names are generated properly
Confirmed that arm container runs on arm64 machine on aws.
> Add Ubuntu 22.04 execution container; Use machine's architecture name for local builds.

- components/core/src/clp/TimestampPattern.cpp
- components/core/src/clp_s/ArchiveWriter.cpp
- components/core/src/clp_s/ColumnReader.cpp
- components/core/src/clp_s/ColumnReader.hpp
- components/core/src/clp_s/ColumnWriter.cpp
- components/core/src/clp_s/ColumnWriter.hpp
- components/core/src/clp_s/JsonParser.cpp
- components/core/src/clp_s/ParsedMessage.hpp
- components/core/src/clp_s/ReaderUtils.cpp
- components/core/src/clp_s/SchemaReader.cpp
- components/core/src/clp_s/SchemaTree.hpp
- components/core/src/clp_s/TimestampDictionaryReader.cpp
- components/core/src/clp_s/TimestampDictionaryWriter.cpp
- components/core/src/clp_s/TimestampPattern.cpp
- components/core/src/clp_s/TimestampPattern.hpp
- components/core/src/clp_s/search/DateLiteral.cpp
- components/core/src/clp_s/search/DateLiteral.hpp
- components/core/src/clp_s/search/EvaluateTimestampIndex.cpp
- components/core/src/clp_s/search/Integral.hpp
- components/core/src/clp_s/search/Literal.hpp
- components/core/src/clp_s/search/NarrowTypes.cpp
- components/core/src/clp_s/search/Output.cpp
- components/core/src/clp_s/search/Output.hpp
- components/core/src/clp_s/search/SearchUtils.cpp
- components/core/src/glt/TimestampPattern.cpp
- components/core/tests/test-TimestampPattern.cpp
Fixes #261 
* Add some obvious variations of existing timestamp patterns to clp, clp-s, and glt
* Add "%E" format specifier to clp-s to capture unix epoch millisecond timestamps found in strings
* Refactor and simplify timestamp column compression code in clp-s
* Fix a nested timestamp bug
* Compressed data with the new timestamp formats and verified that the timestamps were parsed succesfully
* Verified that nested timestamps now exhibit expected behaviour for compression/decompression/search
* Added unit tests in clp for new timestamp formats
* Ingested [cockroachdb](https://zenodo.org/records/10516387) dataset and performed searches on timestamp column
> Add new timestamp formats and refactor timestamp code in clp-s (fixes #261)

- components/core/src/clp_s/clp-s.cpp
- components/core/src/clp_s/search/kql/kql.cpp
- components/core/src/clp_s/search/kql/kql.hpp
- Make no timestamp/schema matches a success return.
- Make error return values consistent.
- Clean-up log messages on lex/parse error.
`clp-s` currently treats no timestamp/schema matches as an error which causes searches from the UI (#250) to fail when no records match the user's query. This PR changes them to success returns and performs some other related clean-up of the return values / log messages.
* Validated compression, decompression, and search of a test file.
* Validated that a search that matched no schemas produced a successful return.
* Validated that a search that matched no timestamp ranges produced a successful return.
* Validated that an invalid query only printed a log about the lex/parse error and produced an error return.
* Validated that missing arguments produced an …
> Clean-up clp-s' CLI error behaviour:

- components/core/src/clp_s/clp-s.cpp
We added support for printing timestamps during search. However, it is be disabled by default when printing to stdout. This PR fixes the misuse of StandardOutputHandler constructor, ensuring that timestamps are not printed to stdout.
+ Built clp-s and compressed part of [mongodb](https://zenodo.org/records/10516285) dataset.
+ Ran query "id: 23285".
> clp-s: Fix incorrect usage of StandardOutputHandler constructor.

- components/core/src/clp_s/CommandLineArguments.cpp
- components/core/src/clp_s/CommandLineArguments.hpp
- components/core/src/clp_s/JsonConstructor.cpp
- components/core/src/clp_s/JsonConstructor.hpp
- components/core/src/clp_s/clp-s.cpp
- components/job-orchestration/job_orchestration/executor/search/fs_search_task.py
- docs/core/clp-structured.md
#259 added support for `clp-s` to be used in the package by changing its behaviour from creating an archive in the given directory to creating an archive as a subdirectory of the given directory. This meant that users could run `clp-s` to compress into "archives-directory" but then decompressing/searching would require the user to specify a subdirectory of "archives-directory".
This PR adds support for `clp-s` to instead automatically iterate over all subdirectories of the given "archives-directory" by default. The package still requires the ability to search a specific archive (one of the subdirectories), so the PR adds a new flag `--archive-id` that, when specified, will only search a subdirectory with the given name (archive ID).
Using `clp-s`:
* Validated compression and decompression …
> clp-s: Add support for decompressing/searching a directory of archives.

- .github/actions/clp-core-build-deps-and-binaries/action.yaml
- .github/workflows/clp-execution-image-build.yaml
In PR (#187 ), we converted the repository names to lowercase before using them. However, there are still two actions using the unconverted repository names. This PR fixes the problem.
> Convert repository names to lowercase before referring to them as docker names.

- .github/actions/clp-core-build-deps-and-binaries/action.yaml
The [clp-core-x86-ubuntu-focal](https://github.com/y-scope/clp/pkgs/container/clp%2Fclp-core-x86-ubuntu-focal) image is not being (re-)built when only clp-core's source files change since the GH actions step is conditional on the dependencies changing. This means that the latest bug fixes to `clp` and `clp-s` have not been getting published to that container image. This PR changes the GH actions step so that it runs if either the dependencies or source files change.
* Merged the change in my fork.
* Merged a source file change in my fork.
* Validated that the action showed that it was being run due to the source files changing and *not* the dependencies changing.
> Build clp-core docker image if source files change.

- .github/actions/clp-core-build-deps-and-binaries/action.yaml
- .github/workflows/clp-execution-image-build.yaml
GitHub action failed: https://github.com/y-scope/clp/actions/runs/7862011912
In PR (#273), the change was incorrect since there is a missing `outputs.` field when referring to the repository name generated in `sanitization`. It was not exposed because, during the development, the actual workflow that instantiates the workflow was never executed. This PR fixes the problem.
In my forked repo, I manually enabled both workflows to ensure the docker names can be properly generated (`"linzhihao-723"`).
> Add missing `outputs` field when referring to the lowered repository names.

- Taskfile.yml
Split the webui build process into two stages webui-bundle and webui to support building a package on arm64 architecture. The bundling stage requires meteor which is only available x64 architecture, so the strategy is to bundle the package on x86_64 and build from arm64 machine
Built AMI with the change and verified that CLP can compress and search results is displayed on webui
> Split webui build into bundling and building to support arm64 builds.

- components/clp-package-utils/clp_package_utils/scripts/native/search.py
- components/clp-package-utils/clp_package_utils/scripts/search.py
- components/core/src/clp_s/CommandLineArguments.cpp
- components/core/src/clp_s/CommandLineArguments.hpp
- components/core/src/clp_s/clp-s.cpp
- components/core/src/clp_s/search/Output.cpp
- components/core/src/clp_s/search/Output.hpp
- components/job-orchestration/job_orchestration/executor/search/fs_search_task.py
- components/job-orchestration/job_orchestration/scheduler/job_config.py
- docs/core/clp-structured.md
- docs/core/clp-unstructured.md
This PR adds case-insensitive search to clp-s souce code and the package
+ Compiled clp-s and compressed a portion of [mongodb](https://zenodo.org/records/10516285) dataset.
+ Executed two queries, `msg: "Initialized Wire Specification"` (for logtype dict test) and `c: repl` (for var dict test). These queries yielded no results without the `--ignore-case` flag but returned results when the flag was applied.
+ Built the package and compressed [hive-24hrs](https://zenodo.org/records/7094921#.Y5JbH33MKHs) dataset using the package
+ Running `sbin/search.sh "org.apache.hadoop.mapred.Task: using resourcecalculatorprocesstree : [ ]"` resulted in no results, while `sbin/search.sh --ignore-case "org.apache.hadoop.mapred.Task: using resourcecalculatorprocesstree : [ ]"` returned relevant results.
> Add case-insensitive search to clp-s source code and the package

- components/core/tools/scripts/lib_install/centos7.4/install-packages-from-source.sh
- components/core/tools/scripts/lib_install/ubuntu-focal/install-packages-from-source.sh
- components/core/tools/scripts/lib_install/ubuntu-jammy/install-packages-from-source.sh
Update the install script to use relative path so the script doesn't need to be launched from a specific directory
Tested with package flow
> Allow source package installation scripts to be called from any directory.

- components/clp-package-utils/clp_package_utils/scripts/compress.py
- components/clp-package-utils/clp_package_utils/scripts/search.py
Remove unnecessary mount from the package_utils scripts. The current docker bind fails if the mount directory doesn't existm but neither compression or decompression script use the mount
The issue can be reproduced by running two CLP packages on two machines, a master package with everything except workers, and a worker package.
Running the compress.sh and search.sh from master package will trigger the error.
Validated by making sure the above error is fixed, and the input can be compressed by workers
> Remove unnecessary docker mounts from compress/search launch scripts.

- components/webui/imports/api/ingestion/server/publications.js
- components/webui/imports/api/search/server/methods.js
- components/webui/imports/ui/SearchView/SearchControls.jsx
- components/webui/imports/ui/SearchView/SearchControls.scss
- components/webui/imports/ui/SearchView/SearchView.jsx
1. Search option `ignore_case` was recently added for `clp-s` (#272). 
1. Add case sensitivity option to search controls.
2. Fix incorrect logger debug message in `StatsCollectionName`.
1. Loaded Web UI in a browser.
2. In the search controls, observed that `Case sensitivity: Insensitive` as the default option. 
3. With `hadoop-24hrs/logs/i-00c90a0f/` compressed, in the Web UI searched with keyword "downloading", `Time Range` as `All Time`, and `Case sensitivity: Insensitive`, and observed "Results count: 376".
4. In the search controls, changed `Case sensitivity` to be `Sensitive` and restarted the search. Observed "Results count: 0".
> Add case sensitivity option to search controls; Fix incorrect logger debug message in `StatsCollectionName`.

- components/clp-package-utils/clp_package_utils/scripts/start_clp.py
Remove the "-it" from the docker command in the start CLP script because cloud-init doesn't support docker with interactive mode
Ran the package locally and on the docker and verifed that the script waits for database and queue to start.
> Remove interactive docker exec calls to allow use in unattended scripts.

- tools/docker-images/clp-execution-base-focal/Dockerfile
- tools/docker-images/clp-execution-base-jammy/Dockerfile
Remove the lines because the copied script is not used for the docker build
Tested manually and verified that the docker can be built and run CLP binaries without any issue
> Remove unnecessary files from execution container images.

- components/core/tools/docker-images/clp-core-ubuntu-focal/Dockerfile
- components/core/tools/docker-images/clp-core-ubuntu-focal/build.sh
- components/core/tools/docker-images/clp-env-base-centos7.4/Dockerfile
- components/core/tools/docker-images/clp-env-base-ubuntu-focal/Dockerfile
- components/core/tools/docker-images/clp-env-base-ubuntu-jammy/Dockerfile
- components/core/tools/scripts/lib_install/centos7.4/README.md
- components/core/tools/scripts/lib_install/ubuntu-focal/README.md
- components/core/tools/scripts/lib_install/ubuntu-focal/install-prebuilt-packages.sh
- components/core/tools/scripts/lib_install/ubuntu-jammy/README.md
- components/core/tools/scripts/lib_install/ubuntu-jammy/install-prebuilt-packages.sh
- tools/docker-images/clp-execution-base-focal/Dockerfile
- tools/docker-images/clp-execution-base-focal/setup-scripts/install-prebuilt-packages.sh
- tools/docker-images/clp-execution-base-jammy/Dockerfile
- tools/docker-images/clp-execution-base-jammy/setup-scripts/install-prebuilt-packages.sh
This PR modifies the generation of the docker images to reduce their final size. This has two benefits:
1. It will be faster for users to pull the containers from GitHub.
2. It will allow us to switch to a GitHub workflow model where we can share container images between jobs.
For (2), our current solution is to build the image and use it all within a single job (e.g., when core's dependencies change in a PR, we need to rebuild the container image before rebuilding core). This requires using a complex set of GitHub actions; besides the complexity, actions are more opaque than jobs and don't allow creation of a DAG of dependencies. Ideally, we should switch to building the container in one job and using it in (multiple) dependent jobs.
Sharing a container image between jobs requires …
> Reduce the size of the clp container images.

- .github/workflows/clp-lint.yaml
- README.md
- Taskfile.yml
- lint-tasks.yml
`Taskfile.yml` is getting quite big so this PR moves the lint tasks into their own Taskfile (`lint-tasks.yml`). This means that all the lint tasks are now in the "namespace", `lint`; so a task like `py-lint-check` is now `lint:py-check`.
This PR also renames some lint tasks for consistency:
* core-lint-check/fix -> lint:cpp-check/fix
* yamllint -> lint:yml-check/fix
* Validated `task`.
* Validated `lint:check`
* Validated `lint:fix`
* Validated lint workflow
> Move lint tasks into their own Taskfile.

- components/core/src/clp_s/ArchiveConstants.hpp
- components/core/src/clp_s/ArchiveReader.cpp
- components/core/src/clp_s/ArchiveWriter.cpp
- components/core/src/clp_s/CMakeLists.txt
- components/core/src/clp_s/JsonParser.cpp
- components/core/src/clp_s/ReaderUtils.cpp
- components/core/src/clp_s/SchemaMap.cpp
- components/core/src/clp_s/SchemaMap.hpp
- components/core/src/clp_s/archive_constants.hpp
This PR introduces constants for the names of each of the core files in clp-s in order to eliminate the possibility of trivial bugs caused by incorrect filenames. This fixes a bug where the tables and table_metdata files were being referred to by different filenames on the reader and writer side.
* validated that compression/decompression/search work as expected
> clp-s: Use constants for core filenames in archive; fix a bug with inconsistent filenames on reader and writer side

- Taskfile.yml
- lint-tasks.yml
This PR addresses a few issues with the tasks in the Taskfile:
* For tasks whose generated files are tracked using the [`status`](https://taskfile.dev/api/#task) method, if a generated file is deleted and that file wasn't in the status check, the task will not be re-run.
* For tasks whose generated files are tracked by listing them as sources:
* The task is only marked complete after two runs (from a clean state).
* If the generated files are deleted after the first run, the task won't detect that it needs to re-run.
* Some tasks were not being re-run when their steps in the Taskfile were changed.
* Some tasks wouldn't be re-run even though the generated files in their dependencies had changed.
Ideally, the solution to most of these issues would be to use the …
> Taskfile: Improve tracking of dependencies and generated files.

- components/core/src/clp_s/JsonParser.cpp
#297 
This PR fixes the bug mentioned in #297 by finding the position of the second quote and extracting the substring.
+ Compressed the log below. The first log message does not contain spaces between `"` and `,`, while the second log message contains 1 or 2 spaces between`"` and `,`.
```
{"t":{"$date":"2023-03-21T23:34:54.576-04:00"},"s":"I",  "c":"NETWORK",  "id":4915701, "ctx":"-","msg":"Initialized wire specification","attr":{"spec":{"incomingExternalClient":{"minWireVersion":0,"maxWireVersion":17},"incomingInternalClient":{"minWireVersion":0,"maxWireVersion":17},"outgoing":{"minWireVersion":6,"maxWireVersion":17},"isInternalClient":true}}}
{"a" : "string clp" , "b": "clp string"  }
```
+ Decompressed the archive. The second log message does not show the bug in #297
``` …
```
> clp-s: Fix incorrect parsing of strings followed by spaces (fixes #297).

- components/clp-package-utils/clp_package_utils/general.py
- components/clp-package-utils/clp_package_utils/scripts/start_clp.py
- components/clp-package-utils/clp_package_utils/scripts/stop_clp.py
The previous package script let docker automatically remove a container if it fails. This makes the debugging harder as the log in the failed container will be removed together, making it harder to identity the cause of failure.
This change:
- Let docker not remove the failed container by default
- Updated utility functions to distinguish if a docker container is running or has exited
- Updated the stop-clp script to not remove failed container by default and warns user about the failed container
The change also includes an update to the MySQL timeout since on some machines 30 seconds are not enough for the database to start
Manually validated the change.
> Iet clp_package_util not remove exited container

- components/clp-package-utils/clp_package_utils/scripts/stop_clp.py
stop_clp.py is failing to stop the clp package due to:
```
Traceback (most recent call last):
File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/home/user/clp/build/clp-package/lib/python3/site-packages/clp_package_utils/scripts/stop_clp.py", line 42, in <module>
def stop_running_container(container_name: str, already_exited_containers: list[str], force: bool):
TypeError: 'type' object is not subscriptable
```
This occurred because one of my previous code review suggestions was accidentally merged without testing on Python 3.8 (the default on Ubuntu 20.04).
* Built the package
* Validated that starting and stopping the package worked: …
> clp-package: Fix Python-typing syntax error in stop_clp.py.

- components/clp-package-utils/clp_package_utils/scripts/compress.py
#305 is caused by an erroneous `finally` statement which *always* removed the container-internal list of paths for compression after it was generated. The reasoning for having a `finally` at all was to remove the generated file if validation of an input path failed. However, the validation (which tried to determine if a path was relative) was pointless since we resolve all input paths before writing them to the output file.
This PR gets rid of the unnecessary validation and the `finally` block.
Validated that the reproduction instructions in #305 didn't cause a failure.
> clp-package: Remove faulty and unnecessary validation

- components/core/src/clp_s/CommandLineArguments.cpp
- components/core/src/clp_s/CommandLineArguments.hpp
- components/core/src/clp_s/ErrorCode.hpp
- components/core/src/clp_s/clp-s.cpp
- components/core/src/clp_s/search/OutputHandler.cpp
- components/core/src/clp_s/search/OutputHandler.hpp
This PR adds a `NetworkOutputHandler` to support sending query results to a network destination for clp-s.
+ Built clp-s and compressed part of [mongodb](https://zenodo.org/records/10516285) dataset.
+ Wrote a server in Python to receive data and print it out. Started the server and got the host and the port.
+ Executed the query `c: REPL` and output the results to stdout and the server. Compared the results.
> clp-s: Add support for sending query results to a network destination.

- components/webui/imports/ui/SearchView/SearchResults.jsx
- components/webui/imports/ui/SearchView/SearchResultsHeader.jsx
- components/webui/imports/ui/SearchView/SearchResultsTable.jsx
- components/webui/imports/ui/SearchView/SearchResultsTable.scss
- components/webui/imports/ui/SearchView/SearchView.jsx
- components/webui/package-lock.json
- components/webui/package.json
1. Internally it was reported that in the Web UI, occasionally no results are loaded when the results "Loading" block becomes visible.
1. Remove `react-visibility-sensor` from `package.json` "dependencies".
2. Detect if the "Loading" block is visible by [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) ([Can I use...](https://caniuse.com/intersectionobserver)). 
3. Clean up dead code. 
1. Built and started the clp-package by `<PROJECT_ROOT>/build/clp-package/start.sh`. 
2. Compressed sample logs `hadoop-24hrs/logs/i-00c90a0f` by `<PROJECT_ROOT>/build/clp-package/compress.sh`. 
3. Searched with query string "123" with `Time range` being "All Time" and observed `Job ID <JOB_ID> | Results count: 176` in the results status bar. Initially …
> webui: Replace `react-visibility-sensor` with `IntersectionObserver` for infinite scrolling.

- components/clp-package-utils/clp_package_utils/scripts/compress.py
- components/clp-package-utils/clp_package_utils/scripts/native/compress.py
- components/job-orchestration/job_orchestration/scheduler/compress/compression_scheduler.py
- components/job-orchestration/job_orchestration/scheduler/job_config.py
The current way of argument passing uses an on-disk file and doesn't handle the case when compress.sh is on a different machine from compression scheduler. This change replace the on-disk file with a list of file paths. 
Manually ran compress.sh with file and input-list arguments and confirmed no error.
> clp-package: Pass input paths to compression scheduler through database rather than file.

- components/core/src/clp_s/ArchiveReader.cpp
#313
Currently, when searching on multiple archives, `m_schema_ids` is not cleared in `ArchiveReader::close()`. It is likely that some matching schema ids in `m_schema_ids` is not valid for the next archive, which leads to an exception when reading tables. This PR fixes this bug.
+ Built clp-s and compressed part of [mongodb](https://zenodo.org/records/10516285) dataset to 1) multiple archives 2) a single archive
+ Executed the query `c: REPL` and compared the results of the two setups.
> clp-s: Fix a bug caused by not clearing m_schema_ids

- components/webui/imports/api/search/collections.js
- components/webui/imports/api/search/constants.js
- components/webui/imports/api/search/server/SearchJobsDbManager.js
- components/webui/imports/api/search/server/methods.js
- components/webui/imports/api/search/server/publications.js
- components/webui/imports/ui/SearchView/SearchControls.jsx
- components/webui/imports/ui/SearchView/SearchResultsTable.jsx
- components/webui/imports/ui/SearchView/SearchView.jsx
The number of search results in MongoDB might be higher than request argument `max_num_results` due to concurrency between workers, but we still want to restrict the view to the latest `max_num_results` of results and handle sorting. 
1. Limit number of results in subscription `results` by `SEARCH_MAX_NUM_RESULTS`.
1. In the `results` subscription handler, instead of setting MongoDB collection find options `limit=visibleSearchResultsLimit` and `sort={...fieldToSortBy}`, always set `limit=SEARCH_MAX_NUM_RESULTS=1000` and `sort=[["timestamp", "desc"]]` so that the subscription always provide the latest `SEARCH_MAX_NUM_RESULTS=1000` results to its subscribers.
2. In the `results` subscriber, set MongoDB collection find options `limit=visibleSearchResultsLimit` and `sort={...fieldToSortBy}` …
> Limit number of results in subscription `results` by `SEARCH_MAX_NUM_RESULTS`.

- components/webui/imports/ui/SearchView/SearchResultsTable.jsx
- components/webui/imports/ui/SearchView/SearchView.jsx
The current sorting mechanism in search results table header is a bit unintuitive - clicking on a descending sorted column removes all sorting conditions, which defaults to sorted-by-timestamp. However, the results have been initially descending sorted by timestamps, which means users need to click the timestamp table header twice to display the logs in ascending timestamp order. 
1. Remove ambiguous `fieldToSortBy` value `null`. 
2. Change the sorting condition UI logics to toggle between `ASCENDING` and `DESCENDING` on the same field. 
3. Change initial sort toggle behaviour - when user requests to sort by some field other than `TIMESTAMP`, set the sorting condition to be the field with `ASCENDING` order; if the field is `TIMESTAMP`, set the sorting condition to be the field with …
> webui: Fix sorting mechanism in search result table.

- components/core/src/clp/clp/CommandLineArguments.cpp
- components/core/src/clp/clp/CommandLineArguments.hpp
- components/core/src/clp/clp/compression.cpp
Add an option to CLP so it doesn't sort the input files. The change is intended to let CLP compress the input paths in the original order so it's easier to write prefetching logic
Manually verified that with flag = "false", files are compressed in the original order. when flag = "true", files are compressed in the ascending order of the last modified time. other inputs will cause CLP to return a warning message
> clp: Add option to control sorting input files for compression.

- components/clp-package-utils/clp_package_utils/scripts/start_clp.py
Improve how --num-cpus argument is parsed. The current argument pasring requries --num-cpus to be specified before the component name. for example : ./start-clp.py --num-cpus 2 compression_worker.
Manually verify the following command runs without issue:
./start-clp.py compression_worker --num-workers 2
./start-clp.py search_worker --num-workers 2
Observed that specifying --num-workers with other components results in an error
> clp-package: Rename --num-cpus to --num-workers; Parse it only when starting compression/search workers.

- components/webui/imports/ui/SearchView/SearchResults.jsx
- components/webui/imports/ui/SearchView/SearchView.jsx
Internally, it was discovered that in the WebUI search results header, the "Results count" is not updated in real time when there are more than `VISIBLE_RESULTS_LIMIT_INITIAL=10` results. Further investigation found that calculation of the count does not reflect real-time number of results in the results cache.
https://github.com/y-scope/clp/blob/00d9835642a3b3b86c366014819e933ee38c8281/components/webui/imports/ui/SearchView/SearchResults.jsx#L49
In the above code, the `resultsMetadata["numTotalResults"]` does not get updated until the job finishes, and that the `searchResults` only contains a number of `visibleSearchResultsLimit` results. 
1. Add a new React state variable which stores the estimated count of documents returned by …
> webui: Display estimated results count in realtime as the query progresses.

- components/clp-package-utils/clp_package_utils/general.py
- components/clp-package-utils/clp_package_utils/scripts/start_clp.py
1. Internally it was found the `compress.sh` and `decompress.sh` scripts are failing because `clp_config.execution_container` is not loaded correctly, when the config is being referenced in scripts other than `start-clp.sh`.
1. Relocate `clp_config.execution_container` name loading call from `start-clp.py` to `general.py`.
1. Manually tested all scripts that references `clp_config.execution_container` in `clp-package` and observed no failure:
- `start-clp.sh`
- `compress.sh`
- `decompress.sh`
- `search.sh`
> Relocate `clp_config.execution_container` name loading call.

- components/webui/README.md
1. The webui docs command-line instructions contains redundant environment variable settings that have been moved into [`components/webui/settings.json`](https://github.com/y-scope/clp/blob/74ac2949a4a34a4687d945229270f2b9d2900e51/components/webui/settings.json). 
2. In the webui docs command-line instructions, environment variable `ROOT_URL` is missing a port number, which can cause [Hot Module Replacement (HMR)](https://docs.meteor.com/packages/hot-module-replacement) to fail when the debug server is not launched on default HTTP port (80). When HMR fails, the browser client does not automatically re-render as the client code changes until developers manually refresh the page inconveniently.
1. Remove redundant environment variables from the webui docs command-line instructions.
2. Add …
> webui: Correct command-line instructions in README.md

- components/clp-package-utils/clp_package_utils/scripts/native/search.py
- components/clp-package-utils/clp_package_utils/scripts/search.py
- components/core/src/clp/ErrorCode.hpp
- components/core/src/clp/clo/CommandLineArguments.cpp
- components/core/src/clp/clo/CommandLineArguments.hpp
- components/core/src/clp/clo/OutputHandler.cpp
- components/core/src/clp/clo/OutputHandler.hpp
- components/core/src/clp/clo/clo.cpp
- components/core/src/clp_s/CommandLineArguments.cpp
- components/core/src/clp_s/CommandLineArguments.hpp
- components/core/src/clp_s/clp-s.cpp
- components/core/src/clp_s/search/Output.cpp
- components/core/src/clp_s/search/Output.hpp
- components/core/src/clp_s/search/OutputHandler.cpp
- components/core/src/clp_s/search/OutputHandler.hpp
- components/core/src/reducer/ConstRecordIterator.hpp
- components/core/src/reducer/RecordGroup.hpp
- components/core/src/reducer/RecordGroupIterator.hpp
- components/core/src/reducer/ServerContext.cpp
- components/core/src/reducer/ServerContext.hpp
- components/job-orchestration/job_orchestration/executor/search/fs_search_task.py
- components/job-orchestration/job_orchestration/scheduler/job_config.py
- components/job-orchestration/job_orchestration/scheduler/search/reducer_handler.py
This PR adds support for performing count aggregations grouped by time buckets. From the command line users can provide the `--time-bucket-size <ms>`  alongside the `--count` option to `/sbin/search.sh` to trigger timeline count aggregations.
This feature will be used to support a result timeline view in the webui.
- Validated that time bucketed count aggregation works correctly with clp and clp-s
> clp-package: Add support for the time bucketed count aggregation.

- components/core/tools/scripts/utils/build-and-run-unit-tests.sh
The last few build-macos GH workflows runs have been timing out without a clear reason. One thing we did notice is this log:
`./tools/scripts/utils/build-and-run-unit-tests.sh: line 20: nproc: command not found`
This PR replaces `nproc` with `getconf _NPROCESSORS_ONLN` which seems to be supported on both Linux and macOS.
The subsequent workflow run seemed to succeed---which may be a fluke or may have resolved the issue. Either way, it's worth fixing the `nproc` issue.
* Validated all clp-core build workflows succeeded.
* Validated `_NPROCESSORS_ONLN` is also available in WSL's Ubuntu.
> gh-actions: Replace nproc call with getconf to support macOS.

- components/webui/imports/api/ingestion/server/StatsDbManager.js
- components/webui/imports/api/ingestion/server/publications.js
- components/webui/imports/api/search/server/SearchJobsDbManager.js
- components/webui/imports/api/search/server/methods.js
- components/webui/imports/utils/DbManager.js
Internally, it was found that any clp-package instances running beyond some intermittent time would face connection error issues in the WebUI. The issue is believed to be related to the [`wait_timeout`](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_wait_timeout) setting, which has a default of `28800 seconds = 8 hours`. By setting it to an even shorter interval of `2 seconds`, the issue was reproduced and the cause was confirmed.
Through a series of experiments and in-depth analysis, several strategies have been identified that may provide a solution to the observed `wait_timeout` problem.
1. **Ineffectiveness of the mysql2 `enableKeepAlive` option**
It has been observed that enabling the `enableKeepAlive` option in `mysql2` connections does not mitigate the …
> webui: Replace MySQL connection with connection pool.

- components/core/src/clp/ffi/ir_stream/byteswap.hpp
- components/core/src/clp/string_utils/string_utils.hpp
Internally, it was found installing [`clp-ffi-py`](https://pypi.org/project/clp-ffi-py/) on Windows 11 gave errors. It was determined that the following needs to be added to support installation on Windows:
1. MSVC equivalent `Extension.extra_compile_args` in setup.py.
2. MSVC compatible `bswap` implementations.
3. MSVC compatible argument types to function `std::from_chars` in `<clp-repo-root>/components/core/src/string_utils.inc`:`convert_string_to_int`.
https://github.com/y-scope/clp-ffi-py/pull/56
1. This PR implements Requirement 2 & 3 from above.
2. Requirement 1 are implemented in https://github.com/y-scope/clp-ffi-py/pull/56 .
See https://github.com/y-scope/clp-ffi-py/pull/56 .
> core: Add support to compile clp::ffi component using MSVC.

- components/core/CMakeLists.txt
- components/core/cmake/Modules/Findspdlog.cmake
- components/core/tools/scripts/lib_install/spdlog.sh
Internally it was found that when the building environment has `libspdlog` pre-installed, the built executables dynamically links to `libspdlog.so`, which is absent in the execution containers and makes the executables non-runnable inside the execution containers. Further investigations have found that:
1. `libspdlog-dev` packages installed by default Ubuntu Jammy & Focal `apt` source only contain a dynamic library (`libspdlog.so`) and does not contain a static one (`libspdlog.a`).
2. CMake command `find_package(spdlog)` finds target `spdlog::spdlog`, but the target is only `SHARED` rather than `STATIC`. When the `SHARED` target is used in `target_link_libraries`, `spdlog` gets linked dynamically, which can be confirmed by command `ldd` on the built executables. Also, the default `spdlog` …
> core: Check for static spdlog library installation to ensure static linking.

- components/clp-package-utils/clp_package_utils/scripts/native/search.py
- components/clp-package-utils/clp_package_utils/scripts/search.py
- components/core/src/clp_s/CMakeLists.txt
- components/core/src/clp_s/search/OutputHandler.cpp
- components/core/src/clp_s/search/OutputHandler.hpp
- components/job-orchestration/job_orchestration/executor/search/fs_search_task.py
- components/job-orchestration/job_orchestration/scheduler/job_config.py
- components/job-orchestration/job_orchestration/scheduler/search/search_scheduler.py
#299 and #324
#299 and #324 add support for sending query results to a network destination. This PR adds a network server to the package to receive query results. 
+ Built the package and compressed [hive-24hrs](https://zenodo.org/records/7094921#.Y5JbH33MKHs) logs using clp
+ Executed `sbin/search.sh "org.apache.hadoop.metrics2.impl.MetricsSystemImpl: ReduceTask metrics system shutdown complete"`. Used WebUI to run the same query. Both returned results as expected.
+ Changed the storage engine to clp-s and compressed first 1,000,000 log messages of [mongodb](https://zenodo.org/records/10516285) dataset.
+ Executed `sbin/search.sh "id: 22419"`. Used WebUI to run the same query. Both returned results as expected.
> Add a network server to the package to receive query results 

- components/webui/imports/ui/SearchView/SearchResults.jsx
- components/webui/imports/ui/SearchView/SearchResultsTable.jsx
Internally, it was found that in the WebUI, when there are too few search results in the table, "results" subscriptions were continuously getting subscribed by the client frequently. Further investigation found the visibility sensor polling interval handler did not get cancelled so long the sensor was visible, and therefore the `visibleSearchResultsLimit` was getting continuously incremented.
1. Check `hasMoreResults` before unnecessarily incrementing `visibleSearchResultsLimit`.
1. `cd <PROJECT_ROOT>; task`
2. `cd ./build/clp-package/sbin; ./start-clp.sh`
3. `./compress.sh ~/samples/hive-24hr/i-00c90a0f/`
4. Opened the WebUI address in a browser.
5. Started a query with string `222` and observed the job finished without error. For the job, subscription `results` was only subscribed once, …
> webui: Don't run SearchResultsLoadSensor polling or increment visibleSearchResultsLimit when there are no more search results.

- components/core/src/clp/LibarchiveFileReader.cpp
- components/core/src/clp/LibarchiveFileReader.hpp
https://github.com/y-scope/clp/issues/241
The previous LibarchiveFileReader implementation doesn't handle the corner case where an compressed file is empty. This fix adds a an extra nullptr check for m_data_block
Specificially, when a file is empty, [line 243](https://github.com/y-scope/clp/blob/df9e7819eb9ebc6c573f6e2cca715f90020c20d5/components/core/src/clp/LibarchiveFileReader.cpp#L243) will trigger a bug because m_data_block_length is set to 0 on eof, but m_pos_in_data_block has an uninitialized value, causing the function to return a negative buffer size.
This change properly initializes the m_pos variables and handles empty files.
Compressed hadoop.tar.gz, openstack.tar.gz. Verified that CLP doesn't fail
Decompressed hadoop-24hrs and confirmed that empty logs are losslessly …
> clp: Fix missing corner case in LibarchiveFileReader::peek_buffered_data when the underlying buffer is empty (fixes: #241).

- components/core/src/clp/clp/FileCompressor.cpp
- components/core/src/clp/clp/FileCompressor.hpp
https://github.com/y-scope/clp/issues/242
The issue identified in https://github.com/y-scope/clp/issues/242 is not a real issue. It was caused by a size change in the validation buffer. so a non-utf8 char that was not detected by the previous 4k buffer size is revealed by 64k buffer. The decision is to let CLP only read the first 4096 bytes of a file for utf8 validation.
Compressed the var-logs and verified that the error observed in issue 242 is gone.
> clp: Add maximum length for utf8 validation (fixes #242).

- components/core/src/clp/clo/clo.cpp
#342 
Previously clo didn't return any results for pure wildcard queries `*` because it skips searching each file. This PR resolves this issue.
+ Built clo and compressed [hive-24hrs](https://zenodo.org/records/7094921#.Y5JbH33MKHs) logs using clp.
+ Executed query `*` on one of the archives using clo and output results to MongoDB.
+ Checked the corresponding collection in MongoDB.
> clo: Fix a bug causing pure wildcard queries to return no results (fixes #342)

- components/clp-py-utils/clp_py_utils/decorators.py
- components/clp-py-utils/clp_py_utils/sql_adapter.py
- components/clp-py-utils/pyproject.toml
- components/job-orchestration/job_orchestration/scheduler/search/search_scheduler.py
- components/job-orchestration/pyproject.toml
This PR makes several changes in sql_adapter.py and search_scheduler.py to improve resilience with database connection issues.
In SQL_Adapter we introduce an option to create a connection pool using sqlalchemy to handle the details of maintaining a pool of living database connections. Since the connect() method can throw we wrap the sqlalchemy connection pool with a class that returns a dummy connection on error, and logs the connection errors (with a mechanism to ensure connection errors are only logged periodically to avoid log spew).
The dummy connection implements the close() method which means all of the code using the connection pool can be written like
```
with contextlib.closing(db_conn_pool.connect()) as db_conn:
...
```
without fear of throwing on the initial connect() call.
In …
> clp-package: Add connection pool option to SQL_Adapter; Make search scheduler resilient to database connection failures

- .github/actions/clp-core-build/action.yaml
- .github/workflows/clp-core-build.yaml
The binaries in the latest ghcr.io/y-scope/clp/clp-core-x86-ubuntu-focal:main are not executable. This is because the [upload-artifacts](https://github.com/actions/upload-artifact?tab=readme-ov-file#permission-loss) action used to transfer the binaries between GH workflows doesn't retain file permissions.
This PR tars the binaries (retaining the file permissions) before uploading them and untars them after downloading them.
* Validated workflows were successful.
* Merged the change to the `main` branch of my fork and verified that the binaries in the published ghcr.io/kirkrodrigues/clp/clp-core-x86-ubuntu-focal:main image were executable.
> gh-actions: Preserve binary permissions with tar before artifact upload.

- components/webui/README.md
- components/webui/package-lock.json
- components/webui/package.json
- lint-tasks.yml
https://github.com/y-scope/clp/pull/351 integrated eslint-config-yscope into the repository.
#356 Added js-check and js-fix lint tasks and also specified `eslint-config-yscope` dependency in both `component/webui/packages.json` and `component/webui/linter/packages.json` to use the `latest` version. However, after there were version upgrades to the `eslint-config-yscope` npm package, the version of the package in this repo is not getting upgraded accordingly in the lint tasks. 
Without manually installing the new version, the IDE ESLint integration is also using the old version. 
1. Replace 'npm install' with 'npm update' in lint tasks configuration.
2. Update webui ESLint IDE integration instructions.
3. Remove dependency "eslint-config-yscope" from webui's package.json.
1. `cd …
> Linting: Add support for always using latest `eslint-config-yscope` package.

- components/core/src/clp_s/ColumnReader.cpp
- components/core/src/clp_s/ColumnReader.hpp
- components/core/src/clp_s/JsonSerializer.hpp
- components/core/src/clp_s/SchemaReader.cpp
This PR makes a few small changes to avoid unnecessary string copies/string allocations during decompression.
This consists of some small changes inside of JsonSerializer to avoid creating temporary strings unnecessarily, and changes to BaseColumnReader to add an api that will append the value from a column directly to a string buffer instead of the old method where we allocate a new string each time extract_value is called.
* Validated that mongodb dataset decompresses exactly the same after this change
* Validated that mongodb dataset gets 1.5x speedup during decompression
> clp-s: Avoid unnecessary string allocation and string copying while marshalling json

- Taskfile.yml
Recent runs of the lint workflow are [failing](https://github.com/y-scope/clp/actions/runs/8823559590/job/24224479242) because when fetching the page of available Node.js downloads, the page is a cached version pointing to a version of node.js that's no longer available.
Thus, this PR adds no-cache headers to the request in an attempt to bypass the cache.
Thanks to @junhaoliao for the investigation and validating the solution.
Validated the lint workflow succeeds now.
> Taskfile: Bypass cache when querying for latest node version.

- components/webui/imports/ui/SearchView/SearchControls/index.jsx
The current placeholder for the query input is `Enter your query...`. Since `clp` and `clp-s` use different query syntaxes, it's a good idea to remind the user in the UI.
This PR uses different placeholders per storage engine:
* clp: `Enter a wildcard query`
* clp-s: `Enter a KQL query`
In a future PR, we should add a help icon somewhere which links to our upcoming docs about the precise syntax for each.
Validated that the placeholder that shows up changes depending on the configured storage engine.
> webui: Make query input placeholder specific to the current storage engine.

- Taskfile.yml
- lint-tasks.yml
This PR cleans up the Taskfiles in this repo and applies a new naming convention for global variables. A future PR will further reorder the tasks to be more logical.
Itemized changes:
* Replaces the `cd` + `tar` sequence with tar's `--directory` argument.
* Moves the lint-venv directory into the build directory, so that it's removed on `task clean` and doesn't pollute the source.
* Deduplicates the venv tasks with a single venv creation task.
* This task now also works on macOS by replicating the functionality of `sed -i` (to avoid differences between `-i` on Linux versus macOS).
* Deduplicates the checksum computation and validation into tasks.
* Since `task` can't call a task as a `status` check, we use a new mechanism for determining when to rerun the task:
* We list the checksum as a …
> Taskfile: Clean up and apply new conventions; Deduplicate checksum handling into reusable tasks.

- components/core/tools/docker-images/clp-env-base-ubuntu-focal/Dockerfile
- components/core/tools/scripts/lib_install/ubuntu-focal/install-prebuilt-packages.sh
- docs/src/dev-guide/components-core/ubuntu-focal-deps-install.md
In #131, we made GCC v10+ a requirement. Since the default version of GCC on Ubuntu Focal is v9, #131 also added set up steps to configure v10 as the compiler on Focal. However, these steps were flawed:
* They were configuring `gcc` and `g++` as the names for the [alternatives](https://linux.die.net/man/8/update-alternatives) whereas Ubuntu usually sets `cc` and `c++` as the names.
* This is why we had to add `cc` and `c++` in #288.
* Adding the alternatives was done as a configuration step rather than as part of the installation.
* The priority of the added alternatives was set to 10/20 rather than something low that wouldn't affect any alternatives the user already had installed and prioritized.
* They were not configuring slave links for the man pages (something the Ubuntu GCC package …
> Refactor Ubuntu Focal gcc-10 setup and update related usage instructions.

- components/core/tools/scripts/lib_install/ubuntu-focal/install-prebuilt-packages.sh
#371 had a typo in it which causes this error when trying to run `components/core/tools/scripts/lib_install/ubuntu-focal/install-all.sh` on an Ubuntu Focal host (not a container):
```text
update-alternatives: renaming cc.1.gz slave link from /usr/share/man/man1/cc.1.gz to /usr/share/mna/man1/cc.1.gz
update-alternatives: error: unable to install '/usr/share/man/man1/cc.1.gz' as '/usr/share/mna/man1/cc.1.gz': No such file or directory
```
This error is not triggered when the script is used inside the container images since there are no man pages installed in the first place.
Ran `components/core/tools/scripts/lib_install/ubuntu-focal/install-all.sh` on an Ubuntu host and verified the error no longer occurs.
> Fix path typo in Ubuntu Focal dependency install script.

- components/core/src/clp/SQLitePreparedStatement.cpp
- components/core/src/clp/SQLitePreparedStatement.hpp
- components/core/src/glt/SQLitePreparedStatement.cpp
- components/core/src/glt/SQLitePreparedStatement.hpp
In the current `SQLitePreparedStatement` implementations, we provide methods to get the column data with the column string names. However, it is functionally incorrect since the underlying `sqlite3_bind_parameter_index` does not return the correct index in the prepared statement. This PR removes these incorrect methods.
- These methods are not used so they should not break any functionalities in theory.
- Ensure the build flow is unaffected.
> core: Remove invalid methods for getting a column's value from a SQLitePreparedStatement.

- components/core/src/clp_s/search/Output.cpp
- components/core/src/clp_s/search/Output.hpp
This PR fixes a performance bug related to churning reallocations on a stack object during scan time. This performance bug mostly affects queries with at least a few filters. There are some other easy-to-fix issues that reduce scan performance (unnecessary use of shared_ptr, etc.) but they require a much larger diff to fix, so they will be left to another PR.
* Validated that queries containing several conditions on mongodb dataset experience significant speedup
> clp-s: Fix performance bug involving unnecessary reallocations of stack object during scan

- components/webui/imports/ui/SearchView/SearchControls/index.jsx
- components/webui/imports/ui/Sidebar/Sidebar.jsx
- components/webui/imports/ui/Sidebar/Sidebar.scss
- components/webui/imports/ui/Sidebar/SidebarButton.jsx
- components/webui/settings.json
#370 Moved most docs into the Sphinx docs site, which is hosted at https://docs.yscope.com/clp/main/
1. Add button link to the CLP docs site.
2. Add button "mailto" link to support email support@yscope.com .
3. Refactor code and remove unused styles.
1. Built and stated CLP package.
2. Manually ran WebUI developing mode following https://docs.yscope.com/clp/main/dev-guide/components-webui.html#running-in-development
4. Clicked on the "Documentation" link, which redirected to the https://docs.yscope.com/clp/main/ site in a new tab.
5. Clicked on the "Email" link, which showed a new email popup by the OS integration.
6. Clicked on all buttons & links on the Sidebar and verified no link / style is broken.
> webui: Add Sidebar buttons that link to docs and support.

- .github/workflows/clp-lint.yaml
- Taskfile.yml
- docs/src/dev-guide/contributing-linting.md
The `lint` tasks are currently failing on macOS because of some Linux-specific command syntax that we're using. This PR switches to Linux/macOS-agnostic command syntax and enables the [clp-lint](https://github.com/y-scope/clp/blob/main/.github/workflows/clp-lint.yaml) workflow for macOS (so we have automated testing for linting on macOS).
Itemized changes:
* Replace `sed --regexp-extended` with `sed -E`.
* Remove `--perl-regexp` from the `grep` call and use the equivalent grep-compatible syntax.
* Make the node version selection Linux/macOS-agnostic.
* Document the requirements for running the linting tools.
* Validated `task lint:check` and `task lint:fix` pass locally on a Linux host.
* Validated the `clp-lint` workflow succeeds.
* Sanity-checked that `task package` still works.
> Add support for linting on macOS and enable GH workflow for macOS.

- components/core/CMakeLists.txt
- components/core/src/clp_s/search/kql/kql.cpp
- components/core/tests/LogSuppressor.hpp
- components/core/tests/test-kql.cpp
This PR adds new unit tests that cover very basic KQL functionality. Over time we will add to these tests so that we can have more confidence when making changes to our KQL grammar and search AST.
* Built unitTest target
* Validated that new unit tests pass
> clp-s: Add basic unit tests for parsing KQL queries.

- components/core/.clang-format
- components/core/src/clp/BufferReader.hpp
- components/core/src/clp/BufferedFileReader.hpp
- components/core/src/clp/Thread.hpp
- components/core/src/clp/clo/CommandLineArguments.cpp
- components/core/src/clp/ir/LogEventDeserializer.cpp
- components/core/src/clp/ir/LogEventDeserializer.hpp
- components/core/src/clp/streaming_archive/MetadataDB.cpp
- components/core/src/clp/streaming_archive/reader/Segment.hpp
- components/core/src/clp_s/CommandLineArguments.cpp
- components/core/src/clp_s/Utils.hpp
- components/core/src/clp_s/search/BooleanLiteral.hpp
- components/core/src/clp_s/search/Output.cpp
- components/core/src/clp_s/search/OutputHandler.hpp
- components/core/src/clp_s/search/clp_search/Grep.cpp
- components/core/src/glt/BufferReader.hpp
- components/core/src/glt/BufferedFileReader.hpp
- components/core/src/glt/ir/LogEventDeserializer.cpp
- components/core/src/glt/ir/LogEventDeserializer.hpp
- components/core/src/glt/streaming_archive/MetadataDB.cpp
- components/core/src/glt/streaming_archive/reader/LogtypeTableManager.hpp
- components/core/src/glt/streaming_archive/reader/Segment.hpp
- components/core/src/glt/streaming_archive/reader/SingleLogtypeTableManager.hpp
- lint-requirements.txt
The current listing tools are set to specific versions in our local linting tasks and GitHub linting workflow. However, these versions are getting outdated. For example, clang has released `clang-format` version 18.1. Linting tool version updating normally includes more formatting standards and bug fixes. We should set the linting tool versions to the latest to apply these updates. Therefore, this PR updates the following things:
- Ensure `lint-requirements.txt`  to install tools with the latest available versions
- Update src files with the latest linting tools and formatting
In the future PR, we should set the workflow to run periodically for health-checking purposes.
- Linting tools worked well using `task` locally in Linux.
- Workflow passed, manually checked the tools installed are …
> linting: Always use latest versions of linting tools; Upgrade clang-format config.

- .github/workflows/clp-lint.yaml
Note: this PR should not be merged before PR #384
This PR schedules our linting workflow to run every midnight in UTC. It shall help us catch linting tool version updates.
The schedule period reference can be found here: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule.
- In a forked repo, configure the period to be every 10 minutes and ensure it runs as scheduled.
> gh-actions: Run linting workflow daily to validate latest linting tool versions.

- lint-tasks.yml
`task lint:yml` doesn't currently treat warnings as errors meaning that an improperly indented comment wouldn't get caught in the lint workflow. Thus, this PR enables `yamllint`'s strict mode.
* Added a comment with way too much indentation to `.yamllint.yml`
* Validated that `task lint:yml` failed even though the violation was just a warning.
> yamllint: Treat warnings as errors.

- .github/workflows/clp-lint.yaml
#385 scheduled the `clp-lint` workflow to run daily at 15:00 UTC instead of the intended 00:15 UTC. This PR fixes the typo.
Validated that a crontab generator generates the same crontab.
> gh-actions: Run scheduled lint workflow at 00:15 rather than 15:00.

- components/core/CMakeLists.txt
- components/core/src/clp/SQLiteDB.cpp
- components/core/src/clp/SQLiteDB.hpp
- components/core/tests/test-SQLiteDB.cpp
Before this PR, we don't have unit test coverage for SQLite Database functionalities. This PR implements a simple SQLite DB unit test, which includes the following testing flow:
1. The test case will create a new database with a fixed testing table schema.
2. Insert data rows into the database.
3. Persist the database to the disk.
4. Open the created database and create indices.
5. Iterate data rows from the database with a certain ordering (with select statement).
6. Ensure the read results are the same as the input data in step 2, with the expected ordering.
Notice that this PR only provides a skeleton for SQLite functionality testing. It doesn't cover all the SQLite db usage we have in the current `clp` implementation. We will add more tests later when we push new SQLite abstracted …
> core: Add unit test to cover basic SQLite functionalities.

- components/package-template/src/etc/clp-config.yml
We missed adding `redis.compression_backend_database` to the template config file in #238. This PR adds it.
* `task`
* `cd build/clp-package`
* Uncommented `etc/clp-config.yml`
* Changed `redis.search_backend_database` from 0 to 1
* Changed `redis.compression_backend_database` from 1 to 0
* Compressed a dataset
* Validated that the keyspace in redis showed db0.
* `docker exec -it clp-redis-<instance-id> redis-cli -h localhost -p 6379`
* `AUTH <redis-password>` (see `etc/credentials.yml`)
* `INFO keyspace`
* Searched for a log
* Validated that the keyspace in redis showed both db0 and db1.
> package: Add redis.compression_backend_database to template config file.

- components/clp-py-utils/clp_py_utils/sql_adapter.py
- components/job-orchestration/job_orchestration/scheduler/search/search_scheduler.py
#393 
Currently, when starting the search scheduler, two types of warning and error logs are printed
```
/opt/clp/lib/python3/site-packages/job_orchestration/scheduler/search/search_scheduler.py:499: DeprecationWarning: The explicit passing of coroutine objects to asyncio.wait() is deprecated since Python 3.8, and scheduled for removal in Python 3.11.
```
```
Traceback (most recent call last):
File "/opt/clp/lib/python3/site-packages/sqlalchemy/pool/base.py", line 374, in _close_connection
self._dialect.do_terminate(connection)
TypeError: DefaultDialect.do_terminate() missing 1 required positional argument: 'dbapi_connection'
Exception during reset or similar
Traceback (most recent call last):
File "/opt/clp/lib/python3/site-packages/sqlalchemy/pool/base.py", line 986, in _finalize_fairy …
```
> clp-package: Fix errors and warnings in search scheduler (fixes #393).

- components/core/src/clp_s/JsonSerializer.hpp
#410 
The JSON serializer does not add a comma after an unstructured array field during decompression, which makes the decompressed log not in a valid JSON format. This PR fixes the bug.
Compressed the logs below and decompressed the archive
```
{"array":[1,2,3],"object":{"key":"value"}}
{"array":[4,5,6]}
```
Without the code change, the decompressed logs are 
```
{"array":[1,2,3]"object":{"key":"value"}}
{"array":[4,5,6}
```
Now they are 
```
{"array":[1,2,3],"object":{"key":"value"}}
{"array":[4,5,6]}
```
> clp-s: Add a comma after unstructured array fields during JSON serialization (fixes #410).

- components/core/src/clp_s/Utils.cpp
- components/core/src/clp_s/Utils.hpp
- components/core/src/clp_s/search/Output.cpp
- components/core/src/clp_s/search/StringLiteral.hpp
- components/core/src/clp_s/search/kql/Kql.g4
- docs/src/user-guide/reference-json-search-syntax.md
#392 
This PR adds the feature requested in #392. Now we can use `?` to match an arbitrary single character on a variable field. However, there are still two limitations.
+ Queries with a `?` in the middle return empty results. This should be fixes by #407.
+ Queries combined with `?`(`*`) and `\?`(`\*`) cannot work well. This will be fixed later.
Compressed the logs below
```
{"a": "Hello world?", "b": "wwoorr\lldd", "c":"*world"}
{"a": "Hello *", "b": "?world"}
```
The queries below all returned correct results
```
b: \?world
b: ?world
b: ?wo?ld
b: wwoorr\\lldd
c: ?world
c: \*world
```
> clp-s: Add support for wildcard queries using "?" on a variable field.

- docs/src/user-guide/core-clp-s.md
- docs/src/user-guide/core-container.md
- docs/src/user-guide/core-overview.md
- docs/src/user-guide/index.md
`clp-s` is designed to compress, decompress, and search dynamically-structured logs beyond just JSON (e.g., XML, Protobuf, etc.), but as implemented, we only support JSON logs. So for now, this PR simplifies the language to just JSON to avoid confusing users.
This PR also changes the "Reference" card to link to the first page in the reference section rather than the last.
* `task docs:serve`
* Validated that the updates look correct.
> docs: Simplify 'dynamically-structured' to 'JSON' and some minor edits.

- components/clp-package-utils/clp_package_utils/scripts/compress.py
- components/clp-package-utils/clp_package_utils/scripts/decompress.py
- components/clp-package-utils/clp_package_utils/scripts/search.py
- components/clp-package-utils/clp_package_utils/scripts/start_clp.py
Docker containers by default use [json-file logging driver](https://docs.docker.com/config/containers/logging/json-file/) which keeps logging to a single file without any log rotation. 
It doesn't cause any issue in the opensource now.
However, if a CLP package component generates logs at a rapid pace due to error, or due to a change in the logging strategy in the future. The default json-file logging driver could potentially lead to a disk space issue. 
In fact, this have caused a real issue before https://github.com/y-scope/clp/issues/393 was fixed.
To avoid the issue, we let docker containers use the [local logging driver](https://docs.docker.com/config/containers/logging/local/), which defaults to use log rotation with 100MB threshold.
1. Built the package and confirmed that the …
> package: Use docker's local logging driver to enable log rotation for package component containers.

- components/core/src/clp_s/search/Output.cpp
#390
This PR fixes #390, which makes wildcard match consistent for both log-text and variable values. It simply sets `add_wildcards` to `false` for all log-text cases.
+ Used clp-s to compress the first 1,000,000 log messages of [mongodb](https://zenodo.org/records/10516285) dataset.
+ Without the code change, query `msg: "wire "` returned four results. Now it returns nothing. And `*wire *` works fine as before.
> clp-s: Don't add implicit wildcards ('*') at the beginning and the end of a query (fixes #390).

- components/core/src/clp_s/search/Output.cpp
- components/core/src/clp_s/search/Output.hpp
- components/core/src/clp_s/search/clp_search/Grep.cpp
- components/core/src/clp_s/search/clp_search/Grep.hpp
- components/core/src/clp_s/search/clp_search/Query.hpp
#403
Previously, when a query did not contain a subquery, it was not evaluated in clp-s. However, in cases where `matchability = SubQueryMatchabilityResult::SupercedesAllSubQueries`, this caused an issue. This PR fixes the bug, which indirectly resolves issue #403. The primary code change aligns clp-s with the behavior of clp in `Grep::process_raw_query`. The relevant code in `clp_s/search/Output.cpp` has also been updated.
+ Validated the example in #403, the query returned all matching results.
+ Compressed first 1,000,000 log messages of [mongodb](https://zenodo.org/records/10516285) dataset. Executed queries below that targets a log-text field:
```
msg: "*wire *"
attr.message.msg: log_remove*
attr.message.msg: "*id 1*"
attr.message.msg: "*journal/WiredTigerLog*LSN*3456*"
```
The query …
> clp-s: Handle cases where clp-string query-parsing falls back to decompress + match (fixes #403).

- components/core/CMakeLists.txt
- components/core/src/clp/ffi/SchemaTree.cpp
- components/core/src/clp/ffi/SchemaTree.hpp
- components/core/src/clp/ffi/SchemaTreeNode.hpp
- components/core/tests/test-ffi_SchemaTree.cpp
This PR introduces a streaming schema tree implementation designed for IR v2. It has the following components:
- `SchemaTreeNode`: A class that specifies the node information for each node in the schema tree, including a unique ID, a parent ID, key name, type, and children IDs.
- `SchemaTree`: A tree built with SchemaTreeNode, with methods to insert/get tree nodes.
- Unit test: unit test cases to cover basic functionality.
Notice that we already have a schema tree implementation in `clp-s`. The reasons to re-implement the schema tree are the following:
- The schema tree node maintains different information to track a tree node:
- The types of schema tree nodes in the IR format differ from those in the Archive format. The types we support in IR format are the following:
- Integer
- Float
- …
> ffi: Add SchemaTree implementation to support the next IR stream format.

- components/core/src/clp/streaming_archive/reader/File.cpp
This PR refactors the implementation of query matching in the `clp` File reader. It has two improvements:
1. Move `Query` level checks out of the subquery traversal loop.
2. Rewrite the subquery traversal loop with shorter indent blocks to improve readability.
Compressed [hive-24hr](https://zenodo.org/records/7094920) dataset and ran wildcard query "*INFO*applic*1*2.6*2?6*application*". Ensured the results returned from `clg` doesn't change after refactoring.
> core-clp: Refactor `streaming_archive::reader::File::find_message_matching_query`.

- components/job-orchestration/job_orchestration/scheduler/search/search_scheduler.py
- components/webui/imports/api/search/server/SearchJobsDbManager.js
This PR addresses several cancellation issues:
+ Previously, when all search tasks completed, sending a cancellation request changed the status to `CANCELLING`. Since the job was already removed from active_jobs, it remained in an intermediate state. This PR ensures that a cancellation request is only sent if the job status is `PENDING` or `RUNNING`. Besides, for completed jobs in `RUNNING` status, even if the cancellation request was sent, the job status is updated to either `SUCCEEDED` or `FAILED` based on the actual completion.
+ The wrong type was passed when handling job cancellation, so that the code never reached cancel_job_except_reducer. This PR fixes this issue.
+ Started the package and compressed the [hive-24hrs](https://zenodo.org/records/7094921#.Y5JbH33MKHs) dataset. 
+ In …
> clp-package: Fix several search job cancellation issues

- components/core/src/clp_s/ArchiveReader.cpp
- components/core/src/clp_s/ArchiveReader.hpp
- components/core/src/clp_s/JsonSerializer.hpp
- components/core/src/clp_s/SchemaReader.cpp
- components/core/src/clp_s/SchemaReader.hpp
This PR implements serialization for structurized arrays. All of the code changes are relegated to SchemaReader and JsonSerializer. Most of the heavy lifting to support serializing arrays was implemented in #355, so this code change mostly consists of code to walk over the schema for different unordered object types and push JsonSerializer ops as appropriate.
* Validated that decompression works correctly for several array corner cases
* Validated that search on arrays returns expected results
> clp-s: Add support for serializing structured arrays.

- docs/src/user-guide/core-clp-s.md
- docs/src/user-guide/reference-json-search-syntax.md
This is a small docs update to record the existence of the array structurization feature. 
This feature must be turned on by ingesting data using the `--structurize-arrays` flag. It can lead to higher compression ratio some of the time by avoiding dictionary pollution (and should lead to higher compression ratio most of the time after some changes to table packing). On the search side it allows users to search for structures inside of arrays using keys containing wildcards (since the array structure is recorded in the MPT), and will typically make searches inside of arrays much faster.
> docs: Add instructions for using clp-s' array structurization feature.

- components/core/src/clp/streaming_archive/Constants.hpp
#412 added a new field to the archive-local metadata DB, but we forgot to update the archive format version. Ordinarily, changing the format without changing the format version could lead to undefined behaviour when opening an archive created with an old version of clp with the latest version of clp; but luckily, this particular change errors-out due to the missing database column.
This PR updates the version.
Validated that opening an archive created with an old version of clp (before b50e140) with the latest version of clp continues to fail.
> core-clp: Update archive format version due to previous format change in #412.

- components/job-orchestration/job_orchestration/scheduler/search/search_scheduler.py
#416 used syntax that isn't supported by Python 3.8 without the `__future__.annotations` import. The effect of this is that the search scheduler can't run with Python 3.8 (and all searches will seemingly freeze).
This PR adds the import.
* Built and started the package in an Ubuntu Focal container
* Compressed some data
* Used `sbin/search.sh` to run a query and ensured that it didn't freeze.
> clp-package: Add Python __future__.annotations import to allow running with Python 3.8.

- .github/workflows/clp-core-build-macos.yaml
- .github/workflows/clp-core-build.yaml
- .github/workflows/clp-execution-image-build.yaml
- .github/workflows/clp-lint.yaml
We're using deprecated versions of [actions/checkout](https://github.com/actions/checkout) and [dorny/paths-filter](https://github.com/dorny/paths-filter). This PR updates them to the latest versions. The release notes don't mention any breaking changes, so this should be safe.
Validated all workflow jobs succeeded with the exception of [ubuntu-focal-binaries-image](https://github.com/y-scope/clp/blob/main/.github/workflows/clp-core-build.yaml#L249) which requires publishing a container image. The changes to this job mirror the others, so it should succeed when necessary.
> gh-actions: Update to latest versions of all actions.

- .github/PULL_REQUEST_TEMPLATE.md
The references section of the PR template is rarely used and rarely necessary since GitHub often highlights references in the PR description.
This PR removes the section. This PR also adds some instructions about setting the PR title. More elaborate instructions will be in our contribution guidelines.
Rendered the markdown and verified the comments weren't displayed.
> pr-template: Remove unnecessary references section and add instructions for the PR title.

- components/clp-package-utils/clp_package_utils/scripts/native/search.py
- components/core/src/clp/clo/OutputHandler.cpp
- components/core/src/clp/clo/OutputHandler.hpp
- components/core/src/clp/clo/clo.cpp
- components/core/src/clp/streaming_archive/reader/Archive.cpp
- components/core/src/clp/streaming_archive/reader/File.cpp
- components/core/src/clp/streaming_archive/reader/Message.cpp
- components/core/src/clp/streaming_archive/reader/Message.hpp
- components/core/src/clp_s/search/OutputHandler.cpp
Current CLP's search results contain the original message, timestamp and original file path. However, the original file path is not sufficient to identify the file if multiple file shares the same path (if they are from different file system, or they are both rotated log with the same file name).
In this PR, we add file's original id and the log event index to every search result, which allows us to locate the specific file split that contains the matching result.
The change can be viewed as two smaller change:
1. We add a new member variable "log_event_ix" in the Message.hpp that tracks the index in the original file. The original "message_number" is renamed to "ix_in_split" to improve clarity.
2. We updated the add_results methods in the output handler  to add log_event_ix and …
> clo: Add orig_file_id and log_event_ix to search results.

- components/webui/imports/api/ingestion/server/publications.js
- components/webui/imports/ui/SearchView/SearchControls/SearchControlsFilterDrawer/SearchControlsTimeRangeInput/index.jsx
- components/webui/imports/ui/SearchView/SearchResults/SearchResultsTable/SearchResultsLoadSensor.jsx
- components/webui/imports/ui/SearchView/SearchResults/SearchResultsTable/index.jsx
- components/webui/imports/ui/SearchView/SearchStatus.jsx
The latest version of [y-scope/eslint-config-yscope](https://github.com/y-scope/eslint-config-yscope) enforces one import per line. This PR applies the new rule to the webui.
Validated lint workflow passes.
> lint: Apply latest version of eslint-config-yscope.

- components/core/src/clp_s/ArchiveReader.cpp
- components/core/src/clp_s/ArchiveReader.hpp
- components/core/src/clp_s/CommandLineArguments.cpp
- components/core/src/clp_s/CommandLineArguments.hpp
- components/core/src/clp_s/JsonConstructor.cpp
- components/core/src/clp_s/JsonConstructor.hpp
- components/core/src/clp_s/SchemaReader.hpp
- components/core/src/clp_s/clp-s.cpp
This PR adds support to decompress a clp-s archive in timestamp order with the `--ordered` command line option. This is implemented by loading all tables into memory, putting them into a min-heap ordered by the timestamp of the next record in each table, and popping from the heap until all records have been decompressed. The timestamp is pulled from the authoritative timestamp column specified at compression time, and if a table does not contain such a column the timestamp is 0 for ordering purposes.
Note: we don't sort by timestamp within each table, so the logs can end up slightly out of timestamp order (this is probably preferred anyway, since it brings us closer to log order).
This seems to add minimal decompression speed overhead (about 2.5%) for fairly typical archives, though would …
> clp-s: Add support for decompression in ascending timestamp order.

- components/log-viewer-webui/.gitignore
- components/log-viewer-webui/README.md
- components/log-viewer-webui/server/.env
- components/log-viewer-webui/server/.gitignore
- components/log-viewer-webui/server/package-lock.json
- components/log-viewer-webui/server/package.json
- components/log-viewer-webui/server/src/app.js
- components/log-viewer-webui/server/src/app.test.js
- components/log-viewer-webui/server/src/main.js
- components/log-viewer-webui/server/src/routes/examples.js
- docs/src/dev-guide/components-log-viewer-webui.md
To integrate the [log-viewer](https://github.com/y-scope/yscope-log-viewer) with the CLP package, we plan to add a new webapp that consists of a React frontend and a Fastify backend:
* The backend will host the log-viewer.
* The backend will also handle requests to decompress an IR file.
* The frontend will embed the log-viewer in an iframe.
* The frontend will also include controls for jumping between different pages/chunks of the IR file, and jumping between different splits of the log file.
We will integrate this new webapp with the package by embedding it in an iframe in the webui.
This convoluted implementation is for two reasons:
* Integrating the log-viewer with the current webui is non-trivial because the webui is written Meteor which doesn't have good support for web workers.
* …
> Add log-viewer-webui component with boilerplate Fastify server.

- components/core/CMakeLists.txt
- components/core/src/clp/ffi/ir_stream/Serializer.cpp
- components/core/src/clp/ffi/ir_stream/Serializer.hpp
- components/core/src/clp/ffi/ir_stream/protocol_constants.hpp
- components/core/tests/test-ir_encoding_methods.cpp
When migrating to the next IR stream format, there are two important differences:
1. The serialization is no longer stateless in the next IR format. The stream has to maintain a schema tree across the entire IR stream.
2. In the current IR format, bytes can be written into the IR buffer in the same order as encoded: first encoded variables, then logtype, and finally timestamp. This is not true in the next IR format. For structured key-value pairs, the overall packet of a new record would be: [new_schema_tree_nodes, keys, values]. Each sub-packet has to be encoded in a separate buffer and merged into one after the entire record is processed. This means we need more than one internal buffer during the serialization, even though only the final merged buffer is exposed to the upper layer …
> ffi: Add WIP Serializer class for the next IR stream format.

- components/core/src/clp_s/CommandLineArguments.cpp
- components/core/src/clp_s/CommandLineArguments.hpp
- components/core/src/clp_s/JsonConstructor.cpp
- components/core/src/clp_s/JsonConstructor.hpp
- components/core/src/clp_s/clp-s.cpp
This PR adds support for chunking the output of timestamp-ordered decompression into several files, where each file has at most the number of records specified in the command line argument. The argument `--ordered-chunk-split-threshold <value>` can be used in conjunction with the `--ordered` argument during decompression to trigger this feature.
- Tested edge case where every records ends up in same chunk
- Tested edge case where num_records % chunk_size == 0
- Tested case where num_records % chunk_size > 0
> clp-s: Add support for chunking output into different files during timestamp-ordered decompression

- components/core/src/clp_s/JsonParser.cpp
- components/core/src/clp_s/JsonParser.hpp
This PR fixes a minor bug where after splitting an archive the print-archive-stats option can be set to a random value.
- Checked that after the archive splits the print-archive-stats option seems to be preserved
> clp-s: Ensure ArchiveWriterOption is fully initialized when splitting archives.

- components/core/src/clp_s/JsonFileIterator.cpp
- components/core/src/clp_s/JsonFileIterator.hpp
- components/core/src/clp_s/JsonParser.cpp
This PR fixes a bug where if an archive is split while halfway through parsing a buffer of JSON objects the entire buffer is attributed to uncompressed size of the first archive instead of being split correctly between the archives before and after the split. We solve this problem by adding a new function to JsonFileIterator which reports the total number of bytes consumed by the caller (as opposed to the total number of bytes read by JsonFileIterator which is what we used before).
* Validated that archives are correctly attributed the right proportion of a buffer of JSON during archive splitting
* Validated that the sum of uncompressed size of all archives is equal to the total file size
> clp-s: Correctly report uncompressed size of archives during archive-splitting (fixes #469).

- components/core/src/clp/clo/clo.cpp
This PR replaces the absolute path in the results cache with relative path. The relative path is preferred because different worker containers may have different mounts, so they may not share the same absolute path.
Manually submitted an IR extraction job and verified that the path in results cache is expected
> clo: Use relative path for file metadata output by an IR extraction job.

- components/clp-package-utils/clp_package_utils/general.py
- components/clp-package-utils/clp_package_utils/scripts/compress.py
- components/clp-package-utils/clp_package_utils/scripts/decompress.py
- components/clp-package-utils/clp_package_utils/scripts/native/compress.py
- components/clp-package-utils/clp_package_utils/scripts/native/decompress.py
- components/clp-package-utils/clp_package_utils/scripts/native/search.py
- components/clp-package-utils/clp_package_utils/scripts/native/utils.py
- components/clp-package-utils/clp_package_utils/scripts/search.py
- components/clp-package-utils/clp_package_utils/scripts/start_clp.py
- components/clp-package-utils/clp_package_utils/scripts/stop_clp.py
This PR factors out the common code used in job submission scripts in clp_package_utils. It also move some query job related functions into a separate util file to prepare an upcoming change that supports ir extraction job in the decompression script.
Launched the package, verified that compression, decompression and search still work from command line
> clp-package: Deduplicate and clean up code in CLI job-launcher scripts.

- Taskfile.yml
- docs/src/dev-guide/components-log-viewer-webui.md
- lint-tasks.yml
This adds the new `log-viewer-webui` component to the JS linting tasks.
To support this change we also:
* Moved and renamed the `linter-nodejs` task into the main Taskfile as `nodejs-latest` since it can be used both for linting and running the `log-viewer-webui`.
* Added tasks to clean the generated files in the source directories of the web-related components.
* Added a task, `log-viewer-webui-node-modules`, to install the dependencies of the `log-viewer-webui`.
* Validated `task lint:js-check` found no violations in the current code.
* Introduced a style violation in each of the log-viewer-webui client, log-viewer-webui server, and webui.
* Validated `task lint-js-check` found each violation (one at a time).
* Validated `task lint:js-fix` fixed all violations.
* Validated `task …
> linting: Add log-viewer-webui to js-lint tasks.

- components/core/src/clp/clp/CMakeLists.txt
- components/core/src/clp/clp/FileCompressor.cpp
- components/core/src/clp/clp/utils.cpp
- components/core/src/clp/clp/utils.hpp
This PR:
1. Replace the UTF-8 buffer validation with dedicated methods introduced in PR #453 
2. Remove UTF-8 validation helpers in the current `clp/utils` as it doesn't validate UTF-8 code point ranges.
1. Add three files into a directory: one valid raw log file, one valid zstd compressed IR file, and `clp` binary. Compress the archive using `clp` and ensure raw log and IR can be properly compressed, but not `clp` binary.
2. Repeat step 1 by first compressing the directory using `zip` to trigger `libarchive` reading path. Ensure the raw log can be properly compressed (but not IR, since libarchive reader will not recursively decompress the zstd compressed IR stream)
3. Ensure workflow passed
> clp-core: Replace calls to incomplete UTF-8 validation function with new and complete implementation.

- Taskfile.yml
- components/clp-package-utils/clp_package_utils/general.py
- components/clp-package-utils/clp_package_utils/scripts/start_clp.py
- components/clp-package-utils/clp_package_utils/scripts/stop_clp.py
- components/clp-py-utils/clp_py_utils/clp_config.py
- components/package-template/src/etc/clp-config.yml
- lint-tasks.yml
This PR adds log_viewer as a component into the CLP package. The PR consists of three small changes.
1. Adds the log_viewer into Taskfile.yml
2. Packages node-22 into the package and distinguish it from the node-14
3. Updates the start-clp script to launch log_viewer
Built a clp package and launched log_viewer
1. Confirmed that the container doesn't generate any error message
2. Tested with example route http://127.0.0.1:3000/examples/get/Alice
3. Started and stopped the log viewer webui with start-clp log_viewer_webui and stop-clp log_viewer_webui
> clp-package: Add log-viewer-webui as a component.

- components/job-orchestration/job_orchestration/executor/query/extract_ir_task.py
- components/job-orchestration/job_orchestration/executor/query/fs_search_task.py
This PR fixes two bugs in query worker scripts, introduced by https://github.com/y-scope/clp/pull/460
1. Fixes a bug where the search results are written to task_id collection. They should be written to job_id collection
2. Fixes a bug where an int is converted to string before joined as part of the command
Tested with log viewer.
> clp-package: Fix bugs introduced in #460:

- components/core/src/clp/streaming_archive/ArchiveMetadata.cpp
In the current CLP archive implementation, we serialize the archive metadata into a file in the compressed archive. When decompressing the archive, we deserialize the metadata. However, the deserialization constructor has a bug to miss the read of `m_creation_idx`. This PR fixes this bug.
Validated on the private repo to ensure the fix works.
> core-clp: Fix ArchiveMetadata deserialization by deserializing previously missed field.

- components/core/src/clp_s/CommandLineArguments.cpp
- components/core/src/clp_s/JsonConstructor.cpp
- components/core/src/clp_s/JsonConstructor.hpp
- components/core/src/clp_s/archive_constants.hpp
- components/core/src/clp_s/clp-s.cpp
This PR introduces the option to record metadata about decompressed archive chunks to mongodb for the purpose of log viewing. The changes are localized to CommandLineArguments and JsonConstructor.
We record the start and end timestamp of each chunk in the start and end index fields of the metadata since that is the information that will be used to look up and order chunks for viewing in the context of clp-s.
- Validated that all decompression modes still work correctly when metadata not recorded
- Validated that errors are reported as expected with invalid mongodb uri and collection arguments
- Validated that expected metadata gets written to mongodb when valid uri and collection are passed
> clp-s: Add option to record metadata about decompressed archive chunks.

- components/core/.clang-format
- components/core/src/clp/regex_utils/ErrorCode.cpp
- components/core/src/clp/regex_utils/ErrorCode.hpp
- components/core/src/clp/regex_utils/constants.hpp
- components/core/src/clp/regex_utils/regex_translation_utils.cpp
- components/core/tests/test-regex_utils.cpp
- docs/src/dev-guide/components-core/regex-utils.md
The regex syntax uses escape sequences to represent its metacharacters literally. 
The translator should de-escape the escaped metacharacter and add it to the wildcard output. Or if the metacharacter is shared by both the regex and the wildcard syntax, it should keep the escape slash.
Escape sequences that escape alphanumeric characters are disallowed since they perform other tasks that are currently not supported by the translator.
Verified in unit tests
> regex-utils: Add support for handling escaped regex metacharacters.

- .gitmodules
- Taskfile.yml
- components/clp-package-utils/clp_package_utils/scripts/start_clp.py
- components/log-viewer-webui/server/settings.json
- components/log-viewer-webui/server/src/app.js
- components/log-viewer-webui/server/src/routes/static.js
Integrate yscope-log-viewer to clp:
1. Add it to `.gitmodules`, putting it within `log-viewer-webui`.
2. Register it in fastify.
3. In `Taskfile.yml`, create checksum and build tasks.
Run `task package`, the build should give no errors.
In `clp/build/clp-package/sbin`, run `start-clp.sh`, access localhost:3000/log-viewer/index.html, observe log viewer is loaded.
> clp-package: Add the log-viewer and serve it using the log-viewer-webui.

- components/core/CMakeLists.txt
- components/core/src/clp/CurlGlobalInstance.cpp
- components/core/src/clp/CurlGlobalInstance.hpp
- components/core/src/clp/NetworkReader.cpp
- components/core/src/clp/NetworkReader.hpp
- components/core/tests/test-NetworkReader.cpp
Before this PR, we reply on static methods `clp::NetworkReader::init/deinit` to initialize `libcurl` global resources. However, there are downsides of the current implementation:
1. Curl resource management should not be specific to a particular application of `libcurl`; there should be a dedicated approach, instead of being a part of `clp::NetworkReader`
2. The current way of doing init/deinit is just a wrapper to `libcurl`'s C style resource management. It has nothing guaranteed about the object life cycle. This is the root cause of some of the workflow failure, such as this one: https://github.com/y-scope/clp/actions/runs/9613911655/job/26517641592, where the global deinit happens before `clp::NetworkReader` instance gets out of its life cycle.
This PR introduces a specialized class …
> core-clp: Add class to encapsulate `libcurl`'s global resource management.

- Taskfile.yml
The current name for package release builds is `clp-<flavour>-ubuntu-focal-<arch>-v<version>`, where items in angle-brackets are populated with the relevant values. This name may imply to users that they can only use the release builds on Ubuntu Focal, but this isn't the case since we run all CLP components in Ubuntu Focal containers.
This PR removes the OS name and version from the package release names to avoid confusion.
Validated that `task clp-text-pkg-tar` and `task clp-json-pkg-tar` built package tars with names that didn't include the OS name and version.
> Taskfile: Remove container OS name and version from built package name.

- components/clp-package-utils/clp_package_utils/scripts/start_clp.py
When running container as root user, redis, results cache and rabbitmq containers lose the write permission to log and data directories.
This PR adds a temporary fix. We let the container run with their default user and change the ownership of the log directories when the current user is root.
Also adds a start up check for redis
1. Run clp package with root, confirmed that package can run properly
2. Run clp package with non-root. Stop and restart the same package as root, confirmed that package can run properly, indicating that ownership of the folders and their contents has been changed successfully
> clp-package: Add support for running package as root (fixes #500).

- components/core/src/clp/regex_utils/ErrorCode.cpp
- components/core/src/clp/regex_utils/ErrorCode.hpp
- components/core/src/clp/regex_utils/constants.hpp
- components/core/src/clp/regex_utils/regex_translation_utils.cpp
- components/core/tests/test-regex_utils.cpp
- docs/src/dev-guide/components-core/regex-utils.md
Implements the following functionality:
* Reduces a character set into a single character if possible.
* A trivial character set containing a single character or a single escaped metacharacter.
* E.g. `[a]` into `a`, `[\^]` into `^`
* If the `case_insensitive_wildcard` config is turned on, the translator can also reduce the
case-insensitive style character set patterns into a single lowercase character:
* E.g. `[aA]` into `a`, `[Bb]` into `b`, `[xX][Yy][zZ]` into `xyz`
Verified in unit tests
> regex-utils: Add support for translating regex character sets into wildcards when possible.

- components/core/CMakeLists.txt
- components/core/src/clp/EncodedVariableInterpreter.cpp
- components/core/src/clp/clg/CMakeLists.txt
- components/core/src/clp/clo/CMakeLists.txt
- components/core/src/clp/clp/CMakeLists.txt
- components/core/src/clp/ir/ClpString.hpp
- components/core/src/clp/ir/EncodedTextAst.hpp
- components/core/src/clp/ir/LogEvent.hpp
- components/core/src/clp/ir/LogEventDeserializer.cpp
- components/core/tests/test-ir_encoding_methods.cpp
This PR adds a dedicated class for parsed and encoded text strings, named `EncodedTextAst`. Essentially, this PR introduces a new concept to split the text message part from the current `LogEvent`, generalizing the tuple of {logtype, dict vars, encoded vars} to its dedicated type.
In the coming PRs, this class will be used to represent encoded text string values in the key-value pair format CLP IR, extending its usage from an unstructured log message to a more general encoded string.
Ensure all unit tests passed after updating `clp::ir::LogEvent` to use `EncodedTextAst`.
> core-clp: Add `EncodedTextAst` class to represent parsed and encoded unstructured text strings.

- Taskfile.yml
1. Upgrade Meteor.js toolchain version to 2.16 in `Taskfile.yaml`.
1. On a freshly cloned CLP build, switch to the PR branch.
2. Ran `task` and observed package build success.
> Taskfile: Upgrade Meteor.js version to 2.16 (fixes #505).

- components/core/src/clp_s/JsonFileIterator.cpp
- components/core/src/clp_s/JsonParser.cpp
- components/core/src/clp_s/JsonParser.hpp
This PR adds reporting for where a parsing error occurs within a JSON file, and fixes an issue where parsing exceptions were sometimes not caught.
We add some code to the main parsing loop to keep track of how many bytes from the current file have been consumed up to the previous record. When an error occurs we are then able to report how many bytes were parsed successfully .
We also wrap the main "parse_line" function in a try/catch block. Even after getting a valid iterator to a record it seems that certain kinds of invalid fields can throw latent errors in simdjson, which previously went uncaught. Instead of trying to add error handling for every single time we access a field within parse_line we just catch the thrown errors.
- Validated that we correctly report 0 bytes parsed when the …
> clp-s: Report exactly where parsing error occurs when parsing JSON (fixes #514).

- components/core/CMakeLists.txt
- components/core/src/clp/Array.hpp
- components/core/tests/test-Array.cpp
In the current CLP, we use unique pointers of C-style arrays across the code base whenever we need a fix-sized buffer. This violates `clang-tidy` suggestions which advocate deprecating C-style arrays. However, existing `std` containers have limitations to use.
- For `std::vector`, it is hard to control the underlying storage. The storage size is controlled by its capacity but not the size. Also, the vector can't be made immutable to use the storage as a buffer to receive data (such as the use case in `NetworkReader`). This means there's no way to avoid reallocation/resizing by mistakes. Declaring a vector and using its underlying `data()` buffer will not provide any safety.
- For `std::array`, the size must be given in the compile time.
Therefore, we introduce our own implementation of …
> core: Add `Array` template class to abstract a fixed-size contiguous buffer whose size is determined at runtime.

- components/webui/imports/ui/SearchView/SearchResults/SearchResultsTable/SearchResultsTable.scss
- components/webui/imports/ui/SearchView/SearchResults/SearchResultsTable/index.jsx
1. webui: Improve display of ExtractIr file links in search results table.
1. Built and started CLP package.
2. Compressed sample files.
3. Loaded WebUI http://localhost:4000 in a browser.
4. Started a search with query string "1" and observed each search result is displayed with its original file path.
5. Changed "Max lines per result" and verified that the UI was rendered correctly.
6. Scrolled to the bottom to load more results and verified that the UI was rendered correctly.
Sample screenshot:
> webui: Improve UI of links for viewing search results in context.

- components/core/src/clp/Defs.h
- components/core/src/clp/DictionaryWriter.hpp
- components/core/src/clp/Grep.hpp
- components/core/src/clp_s/Defs.hpp
- components/core/src/clp_s/DictionaryWriter.hpp
- components/core/src/clp_s/ReaderUtils.hpp
- components/core/src/clp_s/TimestampDictionaryReader.hpp
- components/core/src/clp_s/TimestampDictionaryWriter.hpp
- components/core/src/clp_s/search/ColumnDescriptor.hpp
- components/core/src/clp_s/search/Expression.hpp
- components/core/src/clp_s/search/Integral.hpp
- components/core/src/clp_s/search/Literal.hpp
- components/core/src/clp_s/search/OrOfAndForm.hpp
- components/core/src/glt/Defs.h
- components/core/src/glt/DictionaryWriter.hpp
- components/core/src/glt/Grep.hpp
- components/core/src/glt/streaming_archive/reader/Archive.hpp
Refactored the core code such that all the alias statements with the form 
`typedef [original-type] [your-alias]; `
were instead in the form
`using [your-alias] = [original-type];`
Built and past unit tests
> core: Replace `typedef`s with type aliases.

- components/core/src/clp/regex_utils/CMakeLists.txt
In the current CMake setting of `regex_utils`, we set the visibility of `target_include_directories` to `PRIVATE`, meaning it is only visible to the library. However, the include path `../` should be made public otherwise library users cannot properly include the header without extra configurations in their CMake. This problem is not discovered in the current `unitTest` build because `clp::string_utils` has its CMake settings properly, and `clp::regex_utils` share the same include root with `clp::string_utils`. If we create a new target and only link against `clp::regex_utils`, the include path of the library won't be automatically resolved.
Another issue found is that the library is using `clp::string_utils`, but `clp::string_utils` is not added in the link targets.
This PR solves the …
> regex-utils: Use `PUBLIC` include visibility for public library headers; Add missing link targets.

- components/core/src/clp/spdlog_with_specializations.hpp
- components/core/src/glt/spdlog_with_specializations.hpp
As #524 mentions, the version of fmtlib installed by default using Homebrew has changed from v10 to v11. v11's [release notes](https://github.com/fmtlib/fmt/releases/tag/11.0.0) specify:
> Started enforcing that formatter::format is const for compatibility with std::format (https://github.com/fmtlib/fmt/issues/3447).
Accordingly, this PR updates our `formatter::format` specializations to be `const`.
Validated the [clp-core-build-macos](https://github.com/y-scope/clp/blob/main/.github/workflows/clp-core-build-macos.yaml) workflow now succeeds.
> core: Mark spdlog specialization functions as const (fixes #524).

- components/core/src/clp/NetworkReader.cpp
- components/core/src/clp/NetworkReader.hpp
- components/core/tests/test-NetworkReader.cpp
As introduced in #513, `clp::Array` is a safe substitute for `std::unique_ptr` when we need a runtime-sized array. This PR replaces the use of `std::unique_ptr` with `clp::Array` in `NetworkReader,` where the array is used as the byte buffer to receive bytes from the underlying `libcurl` handler.
This PR should server as an example showing how to refactor the current code base to eliminate the use of `unique_ptr` with our array implementation.
1. Ensure workflows passed.
2. Related unit tests passed.
> core: Replace `std::unique_ptr<char[]>` with `Array<char>` in `NetworkReader`.

- docs/src/dev-guide/building-package.md
This PR adds `python3-dev` as a requirement for building the package and fixes a path to a dependency install script in the docs. `python3-dev` is necessary for installing Python packages that need to build C extensions.
Validated that building the package after installing python3-dev succeeded.
> docs: Fix dependency install script path and add missing requirement for building the package.

- README.md
Add our OSDI'24 paper on JSON log handling to the README.
Not applicable.
> Add OSDI'24 paper on JSON log handling to the README.

- components/clp-package-utils/clp_package_utils/scripts/compress.py
- components/clp-py-utils/clp_py_utils/s3_utils.py
The non-native compress.py script was pulling parse_aws_credentials from s3_utils, which resulted in unintentially adding a boto3 dependency to the package scripts. This PR moves parse_aws_credentials directly into compress.py in order to remove the transitive boto3 dependency.
* Validated that compression script now runs successfully in environment without boto3
* Validated that ingestion form fs and s3 sources still works
> fix(clp-package): Remove transitive boto3 dependency from package compression script.

- deps-tasks.yml
- docs/src/dev-guide/components-core/index.md
Bump `ystdlib-cpp` version so that we can use `ystdlib::containers::Array`.
We do not bump to the newest version because currently CLP build will break upon the `find_package(outcome)` call in [`ystdlib-cpp`](https://github.com/y-scope/ystdlib-cpp/blob/d3fc9804eacb3ee4f156ae0ca37151cb04847580/CMakeLists.txt#L56). We will do so after we switch to use `Task` to manage all our dependencies.
breaking change.
[yscope-contrib-guidelines]: https://docs.yscope.com/dev-guide/contrib-guides-overview.html
> build(deps): Bump `ystdlib-cpp` to the commit before the `outcome` library was added.

- components/log-viewer-webui/client/src/pages/IngestPage/Details/index.tsx
hides Messages and Files cards when using clp-s
breaking change.
Cards changed when settings where modified 
[yscope-contrib-guidelines]: https://docs.yscope.com/dev-guide/contrib-guides-overview.html
> fix(new-webui): Hide the Messages and Files panels when using the clp-s storage engine (resolves #945).

- components/log-viewer-webui/client/vite.config.ts
#995 introduced a top-level await to support settings loading.
However, the vite config was not configured for this leading to an error during build.
This PR changed the vite config to support top-level await on modern browsers.
breaking change.
App now builds. 
[yscope-contrib-guidelines]: https://docs.yscope.com/dev-guide/contrib-guides-overview.html
> fix(new-webui): Support top-level await by updating browser compatibility target in Vite config.
